'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {Droplets} from 'lucide-react'
import {useAuth} from '@/lib/auth'
import {supabase} from '@/lib/supabase'
import {PageHeader} from '@/components/ui/PageHeader'
import {Card} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import {Input,Select} from '@/components/ui/Input'
import {drainageFields,manualDrainageResult as drainageResult,manualDrainageSummary as drainageSummary,drainageNumber,emptyDrainageContext,emptyDrainageValues,type DrainageReading,type DrainageContext} from '@/lib/drainage'
import {treatmentDay} from '@/lib/treatmentCalendar'
import {FieldHelp} from './FieldHelp'
import {withDeadline} from '@/lib/withDeadline'
const labels=['Volume goutteur','EC goutteur','pH goutteur','Volume drain','EC drain','pH drain']
const fmt=(n:number|null)=>n===null?'—':n.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})
type Sheet={farm:string;date:string;context:DrainageContext;rows:DrainageReading[]}
export default function DrainagePage(){const {activeDomain,user}=useAuth();const [query,setQuery]=useState<URLSearchParams|null>(null);useEffect(()=>setQuery(new URLSearchParams(window.location.search)),[]);if(!query)return <p>Chargement…</p>;if(query.get('domain')&&query.get('domain')!==activeDomain?.domain_id)return <p role="alert">Sélectionnez le client de l’intervention pour ouvrir ce lien.</p>;return activeDomain&&user?<Workspace key={`${activeDomain.domain_id}:${user.id}`} domain={activeDomain.domain_id} user={user.id} occurrence={query.get('occurrence')||''}/>:<p>Sélectionnez une société.</p>}
function Workspace({domain,user,occurrence}:{domain:string;user:string;occurrence:string}){
 const key=`farmpilot:drainage:v1:${domain}:${user}${occurrence?`:occurrence:${occurrence}`:''}`
 const [sheet,setSheet]=useState<Sheet>({farm:'',date:treatmentDay(new Date().toISOString()),context:emptyDrainageContext(),rows:[]})
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[selected,setSelected]=useState('')
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(notice==='Modifications non sauvegardées'){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[notice])
 const [cultural,setCultural]=useState<any>(null),[linkError,setLinkError]=useState('')
 const program=cultural?.programs?.find((p:any)=>p.family==='fertigation'&&p.occurrences.some((o:any)=>o.id===occurrence&&!o.cancelled_at))
 const linkedOccurrence=program?.occurrences.find((o:any)=>o.id===occurrence)
 const linkedRecipe=cultural?.recipes?.find((r:any)=>r.id===program?.recipe_id)
 useEffect(()=>{let alive=true;void (async()=>{try{const result=await withDeadline(signal=>supabase.rpc('cultural_workspace',{p_domain:domain}).abortSignal(signal),25000,'Interventions indisponibles. Actualisez la page.');if(result.error)throw result.error;if(alive)setCultural(result.data)}catch(e:any){if(alive)setLinkError(e.message)}})();return()=>{alive=false}},[domain])
 useEffect(()=>{if(!program||!linkedOccurrence||!ready)return;setSheet(current=>({...current,farm:program.farm_id,date:current.rows.length?current.date:treatmentDay(linkedOccurrence.performed_at||linkedOccurrence.planned_at)}));setSelected(current=>program.targets.some((t:any)=>t.greenhouse_id===current)?current:program.targets[0]?.greenhouse_id||'')},[program,linkedOccurrence,ready])
 const [loading,setLoading]=useState(true),[refError,setRefError]=useState(''),[reload,setReload]=useState(0)
 useEffect(()=>{try{const cached=localStorage.getItem(key);if(cached){const parsed=JSON.parse(cached);if(!Array.isArray(parsed.rows)||!parsed.context)throw Error();setSheet(parsed);setSelected(parsed.rows[0]?.greenhouse||'')}}catch{setError('Brouillon local illisible. Exportez vos données avant de poursuivre.')}setReady(true)},[key])
 useEffect(()=>{let alive=true;setLoading(true);setRefError('');void (async()=>{try{
  const [farms,greenhouses]=await withDeadline(signal=>Promise.all([
   supabase.from('farms').select('id,code,name').eq('domain_id',domain).eq('is_active',true).order('name').abortSignal(signal),
   supabase.from('greenhouses').select('id,code,name,farm_id,farms!inner(domain_id)').eq('farms.domain_id',domain).order('code').abortSignal(signal)
  ]),20000,'Chargement trop long. Cliquez sur Actualiser les fermes.')
  if(farms.error)throw farms.error;if(greenhouses.error)throw greenhouses.error;
  if(alive)setData({farms:farms.data||[],greenhouses:greenhouses.data||[]})
 }catch(e:any){if(alive)setRefError(`Fermes et serres indisponibles : ${e.message}`)}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[domain,reload])
 function openSheet(farm:string,date:string){try{
  if(sheet.farm)localStorage.setItem(`${key}:${sheet.farm}:${sheet.date}`,JSON.stringify(sheet))
  const cached=localStorage.getItem(`${key}:${farm}:${date}`)
  const next:Sheet=cached?JSON.parse(cached):{farm,date,context:emptyDrainageContext(),rows:[]}
  if(!Array.isArray(next.rows)||!next.context)throw Error('Feuille illisible')
  localStorage.setItem(key,JSON.stringify(next));setSheet(next);setSelected(next.rows[0]?.greenhouse||'');setNotice('Feuille quotidienne ouverte. Brouillon conservé sur ce navigateur.');setError('')
 }catch{setError('Impossible de changer de feuille sans risque pour le brouillon. Exportez la feuille avant de poursuivre.')}}
 function change(next:Sheet){setSheet(next);setNotice('Modifications non sauvegardées')}
 function context(patch:Partial<DrainageContext>){change({...sheet,context:{...sheet.context,...patch}})}
 function persist(){try{localStorage.setItem(key,JSON.stringify(sheet));if(sheet.farm)localStorage.setItem(`${key}:${sheet.farm}:${sheet.date}`,JSON.stringify(sheet));setNotice('Brouillon enregistré sur ce navigateur uniquement. Non synchronisé avec Supabase.');setError('')}catch{setError('Sauvegarde locale impossible. Exportez la feuille avant de quitter.')}}
 function exportSheet(){const url=URL.createObjectURL(new Blob([JSON.stringify({format:'farmpilot-drainage-1',domain,user,...sheet},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`drainage-${sheet.date}.json`;a.click();URL.revokeObjectURL(url)}
 function add(){if(occurrence&&(!program||!linkedOccurrence)){setError('Intervention de fertigation introuvable ou inaccessible. Aucun relevé ajouté.');return}if(!sheet.farm||!selected||!sheet.context.unit){setError('Choisissez une ferme, une unité de volume et une serre avant d’ajouter un relevé.');return}const now=new Date();const time=new Intl.DateTimeFormat('fr-FR',{timeZone:'Africa/Casablanca',hour:'2-digit',minute:'2-digit'}).format(now);change({...sheet,rows:[...sheet.rows,{id:crypto.randomUUID(),...(program?{intervention:{programId:program.id,occurrenceId:occurrence,recipeId:program.recipe_id,products:program.products}}:{}),greenhouse:selected,time,status:'measured',values:emptyDrainageValues(),measuredBy:user,enteredBy:user,enteredAt:now.toISOString(),context:{...sheet.context}}]});setError('')}
 function update(id:string,patch:Partial<DrainageReading>){change({...sheet,rows:sheet.rows.map(r=>r.id===id?{...r,...patch}:r)})}
 function removeReading(row:DrainageReading){if(!window.confirm(`Supprimer le relevé de ${names(row.greenhouse)} à ${row.time||'heure non renseignée'} ? Enregistrez ensuite la feuille pour conserver cette suppression.`))return;change({...sheet,rows:sheet.rows.filter(r=>r.id!==row.id)})}
 const greenhouses=data?.greenhouses.filter((g:any)=>g.farm_id===sheet.farm&&(!occurrence||program?.targets.some((t:any)=>t.greenhouse_id===g.id)))||[]
 const names=(id:string)=>data?.greenhouses.find((g:any)=>g.id===id)?.name||id
 const visibleRows=sheet.rows.filter(r=>r.greenhouse===selected)
 const groups=selected?[selected]:[]
 return <div className="space-y-5 min-w-0">
  <Link className="text-sm underline" href="/interventions">← Interventions culturales</Link>
  <Card><h2 className="font-semibold mb-2">Intervention de fertigation et solution</h2>{linkError&&<p role="alert" className="text-danger">{linkError}</p>}<label>Intervention / passage<Select aria-label="Intervention drainage" value={occurrence} onChange={e=>{if(notice==='Modifications non sauvegardées'&&!window.confirm('Changer d’intervention ? Sauvegardez votre brouillon avant de quitter si nécessaire.'))return;window.location.assign('/interventions/drainage?'+new URLSearchParams({domain,occurrence:e.target.value}))}}><option value="">Choisir un passage de fertigation</option>{cultural?.programs?.filter((p:any)=>p.family==='fertigation').flatMap((p:any)=>p.occurrences.filter((o:any)=>!o.cancelled_at).map((o:any)=><option key={o.id} value={o.id}>{p.title} · {treatmentDay(o.performed_at||o.planned_at)} · {o.confirmed_at?'Réalisée':'Prévue'}</option>))}</Select></label>{program?<div className="mt-3 space-y-2 text-sm"><p><strong>Solution :</strong> {linkedRecipe?.name||'Recette liée'} · référence {program.recipe_id}</p><p><strong>Produits du programme :</strong> {program.products.map((p:any)=>p.name).join(', ')}</p><p>{linkedOccurrence.confirmed_at?'Passage réalisé':'Passage prévu : ce relevé ne confirme pas la réalisation.'} · Date : {sheet.date}. La composition conservée est celle du programme ; aucune version numérotée n’est inventée.</p><Link className="text-brand underline" href={'/interventions/programmes?'+new URLSearchParams({domain,programme:program.id})}>Ouvrir l’intervention et ses consommations</Link></div>:<p className="text-sm mt-2">{occurrence?'Intervention introuvable, annulée ou en cours de chargement.':'Choisissez une intervention pour rattacher les relevés à la solution. Les anciens brouillons non liés restent accessibles ici.'}</p>}</Card>
  <PageHeader title="Suivi de drainage" subtitle="Fertigation · relevés terrain" icon={Droplets} iconColor="#06b6d4" description="Une feuille par jour et par serre, avec plusieurs relevés horaires et un pourcentage de drainage saisi manuellement."/>
  <div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!ready} onClick={exportSheet}>Exporter la feuille</Button><Button disabled={!ready} onClick={persist}>Sauvegarder le brouillon</Button></div>
  <p className="rounded-lg border border-warning/30 bg-warning/5 p-3 text-sm">Saisie préparatoire : sauvegarde sur ce navigateur uniquement, pas encore dans la base partagée. Aucun mouvement de stock ni coût. Le lien au passage et la composition du programme sont conservés avec les nouveaux relevés liés. Enregistrement partagé dans Supabase non raccordé.</p>
  <div className="flex flex-wrap gap-2 items-center"><Button variant="secondary" disabled={loading} onClick={()=>setReload(v=>v+1)}>{loading?'Chargement des fermes…':'Actualiser les fermes'}</Button>{refError&&<p role="alert" className="text-danger">{refError}</p>}{!loading&&!refError&&data?.farms.length===0&&<p role="status">Aucune ferme active accessible pour ce client. Vérifiez le client sélectionné et vos habilitations.</p>}</div>
  {error&&<p role="alert" className="text-danger">{error}</p>}{notice&&<p role="status" className="text-sm text-brand">{notice}</p>}
  <Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
   <label>Ferme *<FieldHelp name="Ferme"/><Select aria-label="Ferme drainage" disabled={loading||!!occurrence} value={sheet.farm} onChange={e=>openSheet(e.target.value,sheet.date)}><option value="">Choisir une ferme</option>{data?.farms.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</Select></label>
   <label>Date *<FieldHelp name="Date"/><Input aria-label="Date drainage" type="date" disabled={!!occurrence} value={sheet.date} onChange={e=>{if(e.target.value)openSheet(sheet.farm,e.target.value)}}/></label>
   <label>Volumes *<FieldHelp name="Volumes"/><Select aria-label="Unité volumes" value={sheet.context.unit} onChange={e=>context({unit:e.target.value as DrainageContext['unit']})}><option value="">Choisir l’unité</option><option value="mL">mL</option><option value="L">L</option></Select></label>
  </div><p className="text-xs text-fg-tertiary mt-3">Formulaire version 1 · EC en dS/m · heures de Casablanca · mesures par intervalle de collecte, non cumulées.</p></Card>
  <details className="rounded-lg border border-brand/20 bg-brand/5 p-4"><summary className="cursor-pointer font-semibold">À valider avec les experts : dispositif de collecte et paramétrage par serre</summary><ul className="list-disc pl-5 mt-3 space-y-2 text-sm"><li>Le volume goutteur représente combien de goutteurs ? Le drain est collecté sous combien de plants ou de sacs, et avec combien de goutteurs associés ?</li><li>Les deux volumes portent-ils sur le même intervalle ? Quel coefficient et quelle formule faut-il retenir pour ce dispositif ?</li><li>Le dispositif est-il identique dans toutes les serres ? À quelle date chaque configuration prend-elle effet ?</li><li>Quels appareils EC/pH sont utilisés, partagés ou dédiés ? Quelle fréquence d’étalonnage et quels contrôles faut-il imposer ?</li></ul><p className="mt-3 text-sm">Après validation, ces informations pourront être configurées par serre et proposées automatiquement. Pour le moment, elles restent saisies dans le brouillon et conservées avec chaque relevé ; aucun paramétrage partagé n’est encore activé.</p></details>
  <Card><h2 className="font-semibold mb-3">Feuille quotidienne par serre</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
   <label>Serre *<FieldHelp name="Serre"/><Select aria-label="Serre drainage" value={selected} onChange={e=>{setSelected(e.target.value);context({coefficient:'',validFrom:'',recipeVersion:'',planVersion:''})}}><option value="">Choisir une serre</option>{greenhouses.map((g:any)=><option key={g.id} value={g.id}>{g.name}</option>)}</Select></label>
   <label>Instrument EC<FieldHelp name="Instrument EC"/><Input aria-label="Instrument EC" value={sheet.context.ecInstrument} onChange={e=>context({ecInstrument:e.target.value})}/></label>
   <label>Dernier étalonnage EC<FieldHelp name="Dernier étalonnage EC"/><Input type="date" value={sheet.context.ecCalibration} onChange={e=>context({ecCalibration:e.target.value})}/></label>
   <label>Instrument pH<FieldHelp name="Instrument pH"/><Input aria-label="Instrument pH" value={sheet.context.phInstrument} onChange={e=>context({phInstrument:e.target.value})}/></label>
   <label>Dernier étalonnage pH<FieldHelp name="Dernier étalonnage pH"/><Input type="date" value={sheet.context.phCalibration} onChange={e=>context({phCalibration:e.target.value})}/></label>
  </div><p className="text-xs text-fg-secondary my-3">Les instruments sont conservés avec chaque ligne. Saisissez directement D (%) : aucun coefficient ni calcul à partir des volumes n’est utilisé pour le moment.</p><Button onClick={add}>Ajouter un relevé</Button></Card>
  <Card padding="none" className="overflow-hidden"><div className="overflow-x-auto"><table className="tbl w-full min-w-[1150px]"><thead><tr><th>Serre<FieldHelp name="Serre"/></th><th>Heure<FieldHelp name="Heure"/></th>{labels.map(l=><th key={l}>{l}<FieldHelp name={l}/></th>)}<th>D (%)<FieldHelp name="D (%)"/></th><th>Relevé<FieldHelp name="Relevé"/></th><th>Actions</th></tr></thead><tbody>{visibleRows.map((r,index)=>{const result=drainageResult(r,sheet.date);return <tr key={r.id}><td className="whitespace-nowrap">{names(r.greenhouse)}<details className="text-xs"><summary>Contexte</summary><p>Coefficient : {r.context.coefficient||'absent'} · {r.context.validFrom||'date absente'}</p><p>EC : {r.context.ecInstrument||'non renseigné'} · pH : {r.context.phInstrument||'non renseigné'}</p><p>Mesureur : {r.measuredBy}</p><p>{r.intervention?`Intervention : ${r.intervention.programId} · passage : ${r.intervention.occurrenceId} · recette : ${r.intervention.recipeId}`:'Relevé non lié à une intervention'}</p></details></td><td><Input aria-label={`Heure ${index+1}`} type="time" value={r.time} onChange={e=>update(r.id,{time:e.target.value})}/></td>{drainageFields.map((f,i)=>{const v=r.values[f],invalid=v!==''&&(drainageNumber(v)===null||(f.endsWith('Ph')&&Number(v.replace(',','.'))>14));return <td key={f}><Input className="min-w-[90px]" aria-label={`${labels[i]} ${index+1}`} aria-invalid={invalid} disabled={r.status==='not_taken'} inputMode="decimal" placeholder={f.startsWith('drain')&&f!=='drainVolume'&&r.values.drainVolume==='0'?'Sans drain':''} value={v} onChange={e=>update(r.id,{values:{...r.values,[f]:e.target.value}})}/><span className="text-[10px] text-fg-tertiary">{f.endsWith('Volume')?r.context.unit:f.endsWith('Ec')?'dS/m':''}</span>{invalid&&<p className="text-xs text-danger">Valeur à vérifier</p>}</td>})}<td><Input aria-label={`Drainage (%) ${index+1}`} inputMode="decimal" className="min-w-[100px]" disabled={r.status==='not_taken'} value={r.manualPercent||''} aria-invalid={!!r.manualPercent&&result.ratio===null&&r.status==='measured'} onChange={e=>update(r.id,{manualPercent:e.target.value})}/><span className="text-xs">Saisi · %</span>{result.reason&&<p className="text-xs text-warning">{result.reason}</p>}{result.ratio!==null&&result.ratio>100&&<p className="text-xs text-warning">Supérieur à 100 % : vérifiez la valeur saisie.</p>}</td><td><Select aria-label={`État relevé ${index+1}`} value={r.status} onChange={e=>update(r.id,{status:e.target.value as DrainageReading['status']})}><option value="measured">Mesuré</option><option value="not_taken">Non effectué</option></Select></td><td><Button variant="ghost" className="text-danger" aria-label={`Supprimer le relevé ${index+1}`} onClick={()=>removeReading(r)}>Supprimer</Button></td></tr>})}</tbody></table></div>{!visibleRows.length&&<p className="p-6 text-center text-fg-tertiary">Choisissez une serre puis ajoutez ses relevés horaires pour la journée sélectionnée.</p>}</Card>
  <Card><div className="flex flex-wrap items-center gap-3"><Button disabled={!ready||!sheet.farm} onClick={persist}>Enregistrer la saisie</Button><span className="text-sm text-fg-secondary">Enregistrement local de la feuille, sans validation agronomique ni synchronisation Supabase.</span></div>{notice&&<p role="status" className="mt-3 text-sm text-brand">{notice}</p>}{error&&<p role="alert" className="mt-3 text-sm text-danger">{error}</p>}</Card>
  <div className="grid gap-3 md:grid-cols-2">{groups.map(id=>{const rows=sheet.rows.filter(r=>r.greenhouse===id),summary=drainageSummary(rows,sheet.date);return <Card key={id}><h2 className="font-semibold">{names(id)}</h2><p className="text-3xl font-bold text-brand my-3">{fmt(summary.ratio)} {summary.ratio!==null?'%':''}</p><p className="text-sm">Dernier pourcentage saisi de la journée · {summary.valid} relevé(s) renseigné(s)</p><p className="text-xs text-fg-secondary">{summary.missing} non effectué(s) · {summary.incomplete} incomplet(s) · premier drainage positif observé : {summary.firstPositive||'—'}</p><div className="mt-3 space-y-2" aria-label={`Profil horaire ${names(id)}`}>{[...rows].sort((a,b)=>a.time.localeCompare(b.time)).map(r=>{const result=drainageResult(r,sheet.date);return <div key={r.id} className="flex gap-2 items-center text-xs"><span>{r.time||'—'}</span><div className="flex-1 bg-surface-input rounded h-2"><div className="h-2 bg-brand rounded" style={{width:`${Math.min(100,result.ratio||0)}%`}}/></div><span>{fmt(result.ratio)} %</span></div>})}</div><p className="text-xs text-fg-tertiary mt-2">Pourcentages saisis, sans calcul de moyenne journalière ni interpolation. Barres plafonnées visuellement à 100 % ; valeur chiffrée conservée.</p></Card>})}</div>
 </div>
}
