'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {Sprout,FlaskConical} from 'lucide-react'
import {useAuth} from '@/lib/auth'
import {supabase} from '@/lib/supabase'
import {withDeadline} from '@/lib/withDeadline'
import {decimal,irrigationDates,irrigationStatus,waterFormat} from '@/lib/irrigation'
import {culturalQuantity,type CulturalProduct} from '@/lib/cultural'
import {PageHeader} from '@/components/ui/PageHeader'
import {Card} from '@/components/ui/Card'
import {Badge} from '@/components/ui/Badge'
import styles from './programmes.module.css'
import {Button} from '@/components/ui/Button'
import {Input,Select,Textarea} from '@/components/ui/Input'
import {TreatmentCalendar} from '@/components/phyto/TreatmentCalendar'
import {Modal} from '@/components/ui/Modal'

async function rpc(name:string,args:Record<string,unknown>){const r=await withDeadline(signal=>supabase.rpc(name,args).abortSignal(signal),30000,'Réponse trop longue. Actualisez avant de réessayer.');if(r.error)throw r.error;return r.data}
const blank=()=>({title:'',family:'travaux',farm_id:'',campaign_id:'',warehouse_id:'',recipe_id:'',water_liters:'',notes:'',scope_confirmed:false})
const date=(x:string)=>new Date(x).toLocaleString('fr-FR')
export default function CulturalPage(){const {activeDomain,user}=useAuth();return activeDomain&&user?<Workspace key={`${activeDomain.domain_id}:${user.id}`} domain={activeDomain.domain_id} user={user.id}/>:<p>Sélectionnez une société.</p>}
function Workspace({domain,user}:{domain:string;user:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[create,setCreate]=useState(false),[selected,setSelected]=useState(''),[execution,setExecution]=useState('')
 const [form,setForm]=useState(blank),[targets,setTargets]=useState<Record<string,string>>({}),[products,setProducts]=useState<CulturalProduct[]>([])
 const [schedule,setSchedule]=useState<'single'|'exact_dates'|'recurring'>('single'),[dates,setDates]=useState(['']),[frequency,setFrequency]=useState('weekly'),[count,setCount]=useState(5),[interval,setInterval]=useState(1)
 const [filter,setFilter]=useState({farm:'',family:'',status:'',search:'',sort:'date'}),[comment,setComment]=useState('')
 const [actual,setActual]=useState({performed_at:'',water_liters:'',notes:'',deviation_reason:'',homogeneous:false}),[areas,setAreas]=useState<Record<string,string>>({}),[quantities,setQuantities]=useState<Record<string,string>>({}),[manual,setManual]=useState(false)
 const [settings,setSettings]=useState(false),[config,setConfig]=useState<Record<string,{levels:number;alert_days:number}>>({})
 const [consumptionConfirmed,setConsumptionConfirmed]=useState(false),[receipt,setReceipt]=useState('')
 const [actualErrors,setActualErrors]=useState<Record<string,string>>({})
 function focusField(key:string){const el=document.getElementById('actual-'+key);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.focus({preventScroll:true})}
 function clearField(key:string){setActualErrors(current=>{const next={...current};delete next[key];return next})}
 function fieldProps(key:string){return {id:'actual-'+key,'aria-invalid':!!actualErrors[key],'aria-describedby':actualErrors[key]?'actual-error-'+key:undefined,className:actualErrors[key]?'border-danger ring-1 ring-danger':''}}
 function fieldError(key:string){return actualErrors[key]?<span id={'actual-error-'+key} className="block text-danger text-sm mt-1">{actualErrors[key]}</span>:null}
 useEffect(()=>{setActualErrors({})},[execution])
 const pending=useRef<{id:string;input:any}|null>(null),realPending=useRef<{id:string;actual:any}|null>(null),[frozen,setFrozen]=useState(false),[realFrozen,setRealFrozen]=useState(false)
 const working=useRef(false),alive=useRef(true),generation=useRef(0),opened=useRef(false)
 const load=useCallback(async()=>{const n=++generation.current;const d=await rpc('cultural_workspace',{p_domain:domain});if(alive.current&&n===generation.current){setData(d);if(!opened.current){
  opened.current=true;const query=new URLSearchParams(window.location.search)
  if(query.get('domain')&&query.get('domain')!==domain){setError('Ce lien concerne un autre client. Sélectionnez le client correspondant.');return}
  const id=query.get('programme');if(id)setSelected(id)
  if(query.get('family')==='fertigation')setFilter(current=>({...current,family:'fertigation'}))
  if(query.get('recipe')){
   const r=d.recipes.find((r:any)=>r.id===query.get('recipe'))
   if(!r||!d.farms.some((f:any)=>f.id===r.farm_id&&f.can_plan)){setError('Recette indisponible ou habilitation de planification absente pour cette ferme.');return}
   const wh=d.warehouses.find((w:any)=>w.id===query.get('warehouse')&&w.farm_id===r.farm_id)
   let volume='';try{const v=decimal(query.get('volume')||'');if(v>0&&v<=1e12)volume=String(v)}catch{}
   setForm({...blank(),family:'fertigation',farm_id:r.farm_id,recipe_id:r.id,title:r.name,notes:r.notes||'',water_liters:volume,warehouse_id:wh?.id||''});setCreate(true)
  }
 }}},[domain])
 async function run(fn:()=>Promise<void>){if(working.current)return;working.current=true;setBusy(true);setError('');try{await fn()}catch(e:any){if(alive.current)setError(e.message||'Opération impossible')}finally{working.current=false;if(alive.current)setBusy(false)}}
 useEffect(()=>{alive.current=true;void load().catch(e=>{if(alive.current)setError(e.message)});const timer=window.setInterval(()=>{if(!working.current&&document.visibilityState==='visible')void load().catch(e=>{if(alive.current)setError(e.message)})},60000);return()=>{alive.current=false;generation.current++;window.clearInterval(timer)}},[load])
 const p=data?.programs.find((p:any)=>p.id===selected),farm=data?.farms.find((f:any)=>f.id===p?.farm_id)
 const recipe=data?.recipes.find((r:any)=>r.id===form.recipe_id)
 const effective:CulturalProduct[]=form.family==='fertigation'?(recipe?.lines||[]).map((l:any)=>({...l,unit:l.stock_unit,mode:'recipe'})):products
 const plannedArea=Object.values(targets).reduce((s,v)=>{try{return s+decimal(v)}catch{return s}},0)
 const visible=(data?.programs||[]).filter((p:any)=>(!filter.farm||p.farm_id===filter.farm)&&(!filter.family||p.family===filter.family)&&(!filter.status||p.status===filter.status)&&p.title.toLowerCase().includes(filter.search.toLowerCase())).sort((a:any,b:any)=>filter.sort==='title'?a.title.localeCompare(b.title):new Date(a.occurrences[0].planned_at).getTime()-new Date(b.occurrences[0].planned_at).getTime())
 function patch(v:Partial<ReturnType<typeof blank>>){setForm({...form,...v})}
 function build(){
  const missing:string[]=[]
  if(form.title.trim().length<3)missing.push('Titre : au moins 3 caractères')
  if(!form.farm_id)missing.push('Ferme : sélectionnez une ferme')
  if(!form.campaign_id)missing.push('Campagne : sélectionnez une campagne')
  if(!Object.keys(targets).length)missing.push('Plantations : cochez au moins une serre dans la campagne choisie')
  if(form.notes.trim().length<5)missing.push('Consignes : au moins 5 caractères')
  if(missing.length)throw Error('À compléter — '+missing.join(' ; ')+'.')
  if(!form.scope_confirmed)throw Error('Confirmez le périmètre hors phyto et la répartition homogène.')
  const plannedDates=irrigationDates(schedule,schedule==='exact_dates'?dates:[dates[0]],frequency,interval,count)
  const past=plannedDates.find(d=>new Date(d).getTime()<=Date.now())
  if(past)throw Error(`La date prévue du ${date(past)} est déjà passée. Choisissez une heure future, même pour une intervention aujourd’hui. La date réelle sera renseignée après l’application.`)
  const water=form.water_liters?decimal(form.water_liters):0
  for(const l of effective)culturalQuantity(l,plannedArea,water,data.items.find((s:any)=>s.id===l.stock_item_id)?.unit||'')
  return {...form,domain_id:domain,water_liters:water,targets:Object.entries(targets).map(([planting_id,v])=>({planting_id,area:decimal(v)})),products:products.map(l=>({...l,dose:decimal(l.dose)})),dates:plannedDates}
 }
 async function save(){await run(async()=>{if(!pending.current){pending.current={id:crypto.randomUUID(),input:build()};setFrozen(true)}let id;try{id=await rpc('save_cultural_program',{p_id:pending.current.id,p_input:pending.current.input})}catch(e:any){if(e.code){pending.current=null;setFrozen(false)}throw e;}pending.current=null;if(alive.current){setFrozen(false);setCreate(false);setForm(blank());setTargets({});setProducts([]);setSelected(id);await load()}})}
 async function action(kind:string){if(!window.confirm(`${kind==='approve'?'Approuver ce niveau':kind==='reject'?'Refuser':kind==='cancel'?'Annuler le restant':'Soumettre'} : ${p.title} ?`))return;await run(async()=>{await rpc('cultural_action',{p_id:p.id,p_action:kind,p_level:p.current_level,p_comment:comment});setComment('');await load()})}
 function beginActual(o:any){setConsumptionConfirmed(false);setReceipt('');setExecution(o.id);setActual({performed_at:'',water_liters:String(p.water_liters),notes:'',deviation_reason:'',homogeneous:false});setAreas(Object.fromEntries(p.targets.map((t:any)=>[t.planting_id,String(t.area)])));setQuantities(Object.fromEntries(p.products.map((l:any)=>[l.stock_item_id,String(l.quantity)])));setManual(false);realPending.current=null;setRealFrozen(false)}
 function calculated(l:CulturalProduct){const area=Object.values(areas).reduce((s,v)=>s+decimal(v),0);return culturalQuantity(l,area,actual.water_liters?decimal(actual.water_liters):0,l.unit||'')}
 async function confirm(){await run(async()=>{
  if(!realPending.current){
   const issues:Record<string,string>={}
   const done=new Date(actual.performed_at).getTime()
   if(!actual.performed_at||!Number.isFinite(done))issues.date='Date réelle : renseignez la date et l’heure de l’application.'
   else if(done>Date.now())issues.date='Date réelle : l’application ne peut pas être dans le futur.'
   else if(p.approved_at&&done<new Date(p.approved_at).getTime())issues.date='Date réelle : choisissez une date postérieure à l’approbation du programme.'
   try{const water=actual.water_liters?decimal(actual.water_liters):0;const required=data.families.find((f:any)=>f.code===p.family)?.water_required||['fertigation','nutrition_foliaire','qualite_eau'].includes(p.family);if(water<0||water>1e12||(required&&water<=0))throw Error()}catch{issues.water='Eau réelle : renseignez un volume valide'+(p.family==='fertigation'?' supérieur à zéro.':'.')}
   if(p.products.length&&!consumptionConfirmed)issues.consumption='Cochez la confirmation des quantités réellement consommées, hors solution restant en bac.'
   for(const t of p.targets){try{const area=decimal(areas[t.planting_id]);if(area<=0||area>Number(t.area))throw Error()}catch{issues['area-'+t.planting_id]=`Surface ${t.greenhouse} : renseignez une valeur supérieure à zéro et au plus ${waterFormat(Number(t.area))} m².`}}
   if(manual)for(const l of p.products){try{const q=decimal(quantities[l.stock_item_id]);if(q<0||q>99999999.99||Math.abs(q*100-Math.round(q*100))>0.000001)throw Error();if(q!==calculated(l)&&actual.deviation_reason.trim().length<5)issues.reason='Justificatif des écarts : expliquez la différence avec le calcul en au moins 5 caractères.'}catch{if(!Object.keys(issues).some(k=>k==='water'||k.startsWith('area-')))issues['quantity-'+l.stock_item_id]=`Quantité ${l.name} : nombre positif ou nul, avec au plus 2 décimales.`}}
   if(actual.notes.trim().length<5)issues.notes='Observation du réalisé : saisissez au moins 5 caractères.'
   if(!actual.homogeneous)issues.surfaces='Cochez la confirmation de réalisation et de répartition selon les surfaces.'
   setActualErrors(issues)
   if(Object.keys(issues).length){requestAnimationFrame(()=>focusField(Object.keys(issues)[0]));return}
   const input={...actual,performed_at:new Date(actual.performed_at).toISOString(),water_liters:actual.water_liters?decimal(actual.water_liters):0,areas:Object.fromEntries(Object.entries(areas).map(([k,v])=>[k,decimal(v)])),products:p.products.map((l:CulturalProduct)=>({stock_item_id:l.stock_item_id,quantity:manual?decimal(quantities[l.stock_item_id]):calculated(l)}))}
   realPending.current={id:execution,actual:input};setRealFrozen(true)
  }
  const occurrence=realPending.current.id
  try{await rpc('confirm_cultural_occurrence',{p_id:occurrence,p_actual:realPending.current.actual})}catch(e:any){if(e.code){realPending.current=null;setRealFrozen(false)}throw e;}realPending.current=null;if(alive.current){setRealFrozen(false);setExecution('');setReceipt('CULT-'+occurrence);await load()}
 })}
 function copy(){setForm({...blank(),...p.input,water_liters:String(p.water_liters),title:p.title+' — copie',scope_confirmed:false});setTargets(Object.fromEntries(p.targets.map((t:any)=>[t.planting_id,String(t.area)])));setProducts(p.products.map((l:any)=>({...l,dose:String(l.dose)})));setDates(['']);setSchedule('single');setSelected('');setCreate(true)}
 return <div className={`${styles.page} space-y-5`}>
  <Link href="/interventions" className="underline">← Irrigation et interventions</Link>
  <PageHeader title={filter.family==='fertigation'?'Fertigation — interventions':'Interventions culturales'} subtitle="Prescription, validation et exécution" description="Planifiez vos interventions, suivez leur réalisation et contrôlez les besoins en produits." icon={filter.family==='fertigation'?FlaskConical:Sprout} iconColor="#16a34a" actions={<><Button variant="ghost" disabled={busy} onClick={()=>run(load)}>Actualiser</Button><Button disabled={busy||!data?.farms.some((f:any)=>f.can_plan)} onClick={()=>{setForm(current=>({...current,family:filter.family||current.family}));setCreate(true)}}>Nouvelle intervention</Button></>}/>
  <Link className="btn btn-secondary" href="/interventions/drainage">Saisir le drainage</Link><nav aria-label="Parcours interventions" className="flex flex-wrap gap-2"><Button variant={filter.family==='fertigation'?'primary':'secondary'} onClick={()=>setFilter({...filter,family:'fertigation',status:''})}>Fertigation</Button><Button variant={!filter.family?'primary':'secondary'} onClick={()=>setFilter({...filter,family:'',status:''})}>Toutes les interventions</Button><Link className="btn btn-secondary" href="/interventions/fertigation">Recettes de fertigation</Link><Link className="btn btn-secondary" href="/validations">Mes validations</Link></nav>
  <details className="rounded-lg border border-border bg-surface-raised p-3 text-sm"><summary className="cursor-pointer font-semibold">Comment sont gérés le stock et les coûts ?</summary><p className="mt-2 text-fg-secondary">La planification vérifie les besoins sans consommer. Après validation et réalisation sur le terrain, la confirmation débite l’entrepôt choisi et impute les coûts connus selon les surfaces confirmées. La répartition par serre est estimée.</p></details>
  {receipt&&<Card><p role="status" className="font-semibold text-success">Application confirmée — référence {receipt}</p><p className="mt-2 text-sm">Les quantités positives confirmées sont sorties du stock. Les coûts connus sont répartis par surface ; les prix absents restent à rapprocher, les prix provisoires à vérifier.</p><div className="mt-3 flex flex-wrap gap-3"><Link className="underline" href="/stocks/mouvements">Consulter les mouvements</Link><Link className="underline" href="/couts/pilotage">Vérifier les imputations et prix</Link></div></Card>}
  {error&&<div role="alert" className="border border-danger rounded p-3 text-danger">{error}{/cultural_workspace|schema cache/i.test(error)&&<p>Les migrations 135B et 135C doivent être appliquées avant cette recette.</p>}</div>}
  {data&&<>
   <section aria-label="Synthèse des interventions" className="grid grid-cols-2 xl:grid-cols-4 gap-3">{[
    {label:'Brouillons',status:'brouillon',color:'text-fg-secondary',border:'border-l-border'},
    {label:'À valider',status:'soumise',color:'text-warning',border:'border-l-warning'},
    {label:'À réaliser',status:'approuvee',color:'text-brand',border:'border-l-brand'},
    {label:'Terminés',status:'terminee',color:'text-success',border:'border-l-success'}
   ].map(k=><button key={k.status} type="button" aria-label={`Voir les interventions : ${k.label}`} className="text-left rounded-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand" onClick={()=>{setFilter({...filter,status:k.status,search:''});document.getElementById('cultural-list')?.scrollIntoView({behavior:'smooth',block:'start'})}}><Card className={`h-full border-l-[3px] ${k.border}`}><p className="font-mono text-caption uppercase tracking-wide text-fg-tertiary">{k.label}</p><p className={`text-3xl font-bold mt-3 ${k.color}`}>{data.programs.filter((p:any)=>(!filter.family||p.family===filter.family)&&(!filter.farm||p.farm_id===filter.farm)&&p.status===k.status).length}</p><p className="text-caption text-fg-tertiary mt-1">programme(s) · Voir la liste →</p></Card></button>)}</section>
   <p className="text-caption text-fg-tertiary">Synthèse de la ferme et de la famille sélectionnées, avant filtre de statut et recherche.</p>
   <Card><div className="grid gap-3 md:grid-cols-5"><Select aria-label="Filtrer ferme" value={filter.farm} onChange={e=>setFilter({...filter,farm:e.target.value})}><option value="">Toutes les fermes</option>{data.farms.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</Select><Select aria-label="Filtrer famille" value={filter.family} onChange={e=>setFilter({...filter,family:e.target.value})}><option value="">Toutes les familles</option>{data.families.map((f:any)=><option key={f.code} value={f.code}>{f.name}</option>)}</Select><Select aria-label="Filtrer statut" value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">Tous les statuts</option>{Object.entries(irrigationStatus).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><Input aria-label="Rechercher" placeholder="Rechercher…" value={filter.search} onChange={e=>setFilter({...filter,search:e.target.value})}/><Select aria-label="Tri" value={filter.sort} onChange={e=>setFilter({...filter,sort:e.target.value})}><option value="date">Date prévue croissante</option><option value="title">Titre</option></Select></div></Card>
   <TreatmentCalendar cultural requests={visible.flatMap((v:any)=>v.occurrences.map((o:any)=>({
    id:o.id,planned_at:o.planned_at,target_name:v.title,
    status:o.confirmed_at?'executee':o.cancelled_at?'annulee':v.status,
    treatment_request_targets:(v.targets||[]).map((t:any)=>({campaign_planting_id:t.planting_id})),
    treatment_request_products:v.products.map((l:any)=>({product_name:l.name})),
    stock_forecast:['soumise','approuvee'].includes(v.status)&&!o.confirmed_at&&!o.cancelled_at?{stock_status:data.forecast.some((f:any)=>f.occurrence_id===o.id&&Number(f.missing)>0)?'manquant':'disponible'}:null,
    program:{...v,rowId:o.id,status:o.confirmed_at?'terminee':o.cancelled_at?'annulee':v.status,occurrences:[o]}
   })))} plantings={data.plantings.map((t:any)=>({id:t.id,greenhouses:{id:t.greenhouse_id||t.id,name:t.name,farm_id:t.farm_id,farms:data.farms.find((f:any)=>f.id===t.farm_id)}}))}>{calendarRows=><>
   <section id="cultural-list" className="scroll-mt-24 min-w-0"><div className="flex flex-wrap justify-between items-center gap-2 mb-3"><h2 className="font-semibold">Interventions planifiées · {calendarRows.length}</h2><Button variant="ghost" size="sm" onClick={()=>setFilter({...filter,farm:'',status:'',search:'',sort:'date'})}>Réinitialiser les filtres</Button></div>
   <Card className="overflow-hidden" padding="none"><div className="overflow-x-auto"><table className="tbl min-w-[850px] w-full"><thead><tr><th>Date prévue</th><th>Serres</th><th>Programme / produits</th><th>Statut</th><th>Actions</th></tr></thead><tbody>
   {calendarRows.map((r:any)=>r.program).map((v:any)=>{const outstanding=v.occurrences.filter((o:any)=>!o.confirmed_at&&!o.cancelled_at),missing=data.forecast.filter((r:any)=>r.program_id===v.id&&Number(r.missing)>0),next=[...(outstanding.length?outstanding:v.occurrences)].sort((a:any,b:any)=>new Date(a.planned_at).getTime()-new Date(b.planned_at).getTime())[0];return <tr key={v.rowId}><td className="whitespace-nowrap align-top">{next?date(next.planned_at):'—'}<p className="text-caption text-fg-tertiary mt-1">{data.warehouses.find((w:any)=>w.id===v.warehouse_id)?.name||'Sans produit'}</p></td><td className="min-w-[180px] align-top"><div className="flex flex-wrap gap-1">{(v.targets||[]).map((t:any)=><Badge key={t.planting_id} variant="outline">{t.greenhouse||data.plantings.find((x:any)=>x.id===t.planting_id)?.name||'Serre'}</Badge>)}</div><p className="text-caption text-fg-tertiary mt-2">{data.farms.find((f:any)=>f.id===v.farm_id)?.name}</p></td><td className="min-w-[220px] align-top"><strong>{v.title}</strong><p className="text-caption text-fg-tertiary">{data.families.find((f:any)=>f.code===v.family)?.name}</p><div className="mt-2 space-y-1">{v.products.map((l:any)=><p key={l.stock_item_id} className="text-sm">{l.name} · {waterFormat(l.quantity)} {l.unit}</p>)}</div></td><td className="min-w-[200px] align-top"><Badge variant={v.status==='terminee'?'success':v.status==='soumise'?'warning':v.status==='approuvee'?'brand':v.status==='rejetee'?'danger':'default'}>{irrigationStatus[v.status]||v.status}</Badge><p className="text-caption text-fg-secondary mt-2">{v.occurrences.filter((o:any)=>o.confirmed_at).length} réalisée(s) / {v.occurrences.length}</p>{v.status==='soumise'&&<p className="text-caption">Niveau {v.current_level}/{v.required_levels}</p>}{missing.length>0&&<details className="mt-2 rounded-lg border border-warning/30 bg-warning/5 p-2"><summary className="text-warning cursor-pointer text-caption">Stock manquant · {new Set(missing.map((r:any)=>r.occurrence_id)).size} occurrence(s)</summary>{missing.map((r:any,i:number)=><p key={i} className="text-caption mt-1">{r.product} : {waterFormat(Number(r.missing))} {r.unit}</p>)}</details>}{v.status==='approuvee'&&outstanding.some((o:any)=>new Date(o.planned_at).getTime()<Date.now())&&<div className="mt-2"><Badge variant="danger">En retard</Badge></div>}</td><td className="align-top"><Button size="sm" aria-label={`Ouvrir ${v.title}`} onClick={()=>{setSelected(v.id);setComment('')}}>Ouvrir</Button></td></tr>})}
   </tbody></table></div></Card></section>
   {!calendarRows.length&&<Card>Aucune intervention pour ces filtres.</Card>}
   </>}</TreatmentCalendar>
   {data.can_configure&&<Card><Button variant="ghost" onClick={()=>{setConfig(Object.fromEntries(data.families.map((f:any)=>[f.code,{levels:f.levels,alert_days:f.alert_days}])));setSettings(!settings)}}>Paramétrer validations et alertes</Button>{settings&&<div className="space-y-3 mt-3"><p>0 = désactivée, 1 ou 2 = personnes distinctes, toujours différentes du demandeur. Les paramètres s’appliquent aux prochaines soumissions.</p>{data.families.map((f:any)=><div key={f.code} className="grid gap-2 md:grid-cols-4 items-center"><span>{f.name}</span><label>Niveaux<Select aria-label={`Niveaux ${f.name}`} value={config[f.code]?.levels??1} onChange={e=>setConfig({...config,[f.code]:{...config[f.code],levels:Number(e.target.value)}})}>{[0,1,2].map(n=><option key={n}>{n}</option>)}</Select></label><label>Anticipation stock (jours)<Input aria-label={`Alerte ${f.name}`} type="number" min={0} max={365} value={config[f.code]?.alert_days??15} onChange={e=>setConfig({...config,[f.code]:{...config[f.code],alert_days:Number(e.target.value)}})}/></label><Button disabled={busy} onClick={()=>run(async()=>{await rpc('set_cultural_settings',{p_domain:domain,p_family:f.code,p_levels:config[f.code].levels,p_alert_days:config[f.code].alert_days});await load()})}>Enregistrer {f.name}</Button></div>)}</div>}</Card>}
  </>}
  {create&&data&&<Modal title="Nouvelle intervention culturale" size="lg" onClose={()=>!busy&&setCreate(false)}><div className="space-y-4">
   <fieldset disabled={busy||frozen} className="space-y-3 min-w-0">
    <label className="block">Titre *<Input aria-label="Titre" value={form.title} maxLength={160} onChange={e=>patch({title:e.target.value})}/><span className="text-xs text-fg-tertiary">3 caractères minimum.</span></label>
    <div className="grid gap-3 sm:grid-cols-2"><label>Famille *<Select aria-label="Famille" value={form.family} onChange={e=>{patch({family:e.target.value,recipe_id:''});setProducts([])}}>{data.families.map((f:any)=><option key={f.code} value={f.code}>{f.name}</option>)}</Select></label><label>Ferme *<Select aria-label="Ferme" value={form.farm_id} onChange={e=>{patch({farm_id:e.target.value,campaign_id:'',warehouse_id:'',recipe_id:''});setTargets({})}}><option value="">Choisir</option>{data.farms.filter((f:any)=>f.can_plan).map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</Select></label><label>Campagne *<Select aria-label="Campagne" value={form.campaign_id} onChange={e=>{patch({campaign_id:e.target.value});setTargets({})}}><option value="">Choisir</option>{data.campaigns.filter((c:any)=>c.farm_id===form.farm_id).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label><label>Eau globale par occurrence (L)<Input aria-label="Eau prévue" inputMode="decimal" value={form.water_liters} onChange={e=>patch({water_liters:e.target.value})}/></label></div>
    <div className="border rounded p-3 space-y-2"><strong>Plantations et surfaces concernées *</strong>{data.plantings.filter((t:any)=>t.farm_id===form.farm_id&&t.campaign_id===form.campaign_id).map((t:any)=><div key={t.id} className="flex flex-wrap items-center gap-3"><label><input type="checkbox" checked={t.id in targets} onChange={e=>{const next={...targets};if(e.target.checked)next[t.id]=String(t.area);else delete next[t.id];setTargets(next)}}/> {t.name} · {t.variety}</label>{t.id in targets&&<Input className="w-32" aria-label={`Surface ${t.name}`} inputMode="decimal" value={targets[t.id]} onChange={e=>setTargets({...targets,[t.id]:e.target.value})}/>}</div>)}<p>Total : {waterFormat(plannedArea)} m². Les surfaces du référentiel ne sont pas modifiées.</p></div>
    {form.farm_id&&form.campaign_id&&!data.plantings.some((t:any)=>t.farm_id===form.farm_id&&t.campaign_id===form.campaign_id)&&<p className="rounded border border-warning p-3 text-sm">Aucune plantation disponible pour cette ferme et cette campagne. Vérifiez la campagne ou créez une plantation dans le module Plantations, puis actualisez cette page.</p>}
    <label className="block">Objectif / tâche / consignes *<Textarea aria-label="Consignes" value={form.notes} onChange={e=>patch({notes:e.target.value})}/><span className="text-xs text-fg-tertiary">5 caractères minimum. Les consignes de la recette sont reprises lorsqu’elles existent.</span></label>
    <label className="block">Planification<Select aria-label="Planification" value={schedule} onChange={e=>setSchedule(e.target.value as typeof schedule)}><option value="single">Une date</option><option value="exact_dates">Dates précises</option><option value="recurring">Fréquence définie</option></Select></label>
    <p className="text-sm text-fg-secondary">Dates prévues : choisissez une date et une heure futures, dans les trois prochaines années, sans doublons. Aujourd’hui est possible si l’heure n’est pas encore passée. Les heures sont celles de votre appareil.</p>
    {(schedule==='exact_dates'?dates:[dates[0]]).map((d,i)=><div key={i} className="flex gap-2"><Input aria-label={`Date ${i+1}`} type="datetime-local" value={d} onChange={e=>setDates(dates.map((v,j)=>j===i?e.target.value:v))}/>{schedule==='exact_dates'&&dates.length>1&&<Button variant="ghost" onClick={()=>setDates(dates.filter((_,j)=>i!==j))}>Retirer date</Button>}</div>)}
    {schedule==='exact_dates'&&<Button variant="ghost" disabled={dates.length>=100} onClick={()=>setDates([...dates,''])}>Ajouter date</Button>}
    {schedule==='recurring'&&<div className="grid gap-3 sm:grid-cols-3"><Select aria-label="Fréquence" value={frequency} onChange={e=>setFrequency(e.target.value)}>{Object.entries({daily:'Quotidienne',weekly:'Hebdomadaire',monthly:'Mensuelle',quarterly:'Trimestrielle',yearly:'Annuelle'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><label>Intervalle<Input aria-label="Intervalle" type="number" min={1} max={365} value={interval} onChange={e=>setInterval(Number(e.target.value))}/></label><label>Occurrences<Input aria-label="Occurrences" type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div>}
    <p className="text-sm">Fuseau des dates : {Intl.DateTimeFormat().resolvedOptions().timeZone}. Jusqu’à 100 occurrences, horizon 3 ans.</p>
    {form.family==='fertigation'?<label className="block">Recette de solution finale *<Select aria-label="Recette" value={form.recipe_id} onChange={e=>patch({recipe_id:e.target.value})}><option value="">Choisir une recette</option>{data.recipes.filter((r:any)=>r.farm_id===form.farm_id).map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></label>:<Button variant="ghost" disabled={products.length>=30} onClick={()=>setProducts([...products,{stock_item_id:'',mode:'fixed',dose:''}])}>Ajouter un produit / consommable</Button>}
    {effective.map((l,i)=>{const item=data.items.find((s:any)=>s.id===l.stock_item_id);let q='—';try{q=waterFormat(culturalQuantity(l,plannedArea,form.water_liters?decimal(form.water_liters):0,item?.unit||''))}catch{}return <div key={i} className="border rounded p-3 space-y-2">{form.family==='fertigation'?<strong>{l.name} · {l.dose} {l.dose_unit}</strong>:<><Select aria-label={`Produit ${i+1}`} value={l.stock_item_id} onChange={e=>setProducts(products.map((p,j)=>j===i?{...p,stock_item_id:e.target.value}:p))}><option value="">Article hors phyto</option>{data.items.map((s:any)=><option key={s.id} value={s.id} disabled={products.some((p,j)=>j!==i&&p.stock_item_id===s.id)}>{s.name} ({s.unit})</option>)}</Select><div className="grid gap-2 sm:grid-cols-2"><Select aria-label={`Base ${i+1}`} value={l.mode} onChange={e=>setProducts(products.map((p,j)=>j===i?{...p,mode:e.target.value as CulturalProduct['mode']}:p))}><option value="fixed">Quantité globale par occurrence</option><option value="ha">Unité de stock / hectare</option><option value="m3">Unité de stock / m³ d’eau</option></Select><Input aria-label={`Dose ${i+1}`} inputMode="decimal" value={l.dose} onChange={e=>setProducts(products.map((p,j)=>j===i?{...p,dose:e.target.value}:p))}/></div><Button variant="ghost" onClick={()=>setProducts(products.filter((_,j)=>j!==i))}>Retirer produit {i+1}</Button></>}<p>Quantité prévue par occurrence : {q} {item?.unit}</p></div>})}
    {!!effective.length&&<label className="block">Entrepôt de la ferme *<Select aria-label="Entrepôt" value={form.warehouse_id} onChange={e=>patch({warehouse_id:e.target.value})}><option value="">Choisir</option>{data.warehouses.filter((w:any)=>w.farm_id===form.farm_id).map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></label>}
    <label className="flex gap-2"><input type="checkbox" checked={form.scope_confirmed} onChange={e=>patch({scope_confirmed:e.target.checked})}/>Je confirme que ces produits relèvent du parcours hors phyto, que leurs usages sont adaptés, et que les quantités seront réparties proportionnellement aux surfaces indiquées.</label>
   </fieldset>
   {error&&<p role="alert" className="text-danger">{error}</p>}<Button disabled={busy} onClick={save}>{busy?'Traitement…':frozen?'Réessayer le même programme':'Enregistrer le brouillon'}</Button>
  </div></Modal>}
  {p&&!execution&&<Modal title={p.title} size="lg" onClose={()=>!busy&&setSelected('')}><div className="space-y-3"><p>{irrigationStatus[p.status]} · {data.families.find((f:any)=>f.code===p.family)?.name} · {farm?.name}</p><p>{p.input.notes}</p><p>Eau : {waterFormat(p.water_liters)} L / occurrence. Entrepôt : {data.warehouses.find((w:any)=>w.id===p.warehouse_id)?.name||'Sans produit'}.</p><p>{p.targets.map((t:any)=>`${t.greenhouse} : ${waterFormat(t.area)} m²`).join(' · ')}</p>
   {p.products.map((l:any)=><p key={l.stock_item_id}>{l.name} : {waterFormat(l.quantity)} {l.unit} / occurrence</p>)}
   {p.occurrences.map((o:any)=>{const missing=data.forecast.filter((r:any)=>r.occurrence_id===o.id&&Number(r.missing)>0);return <div className="border rounded p-3" key={o.id}>{p.family==='fertigation'&&!o.cancelled_at&&<Link className="btn btn-secondary mb-2" href={'/interventions/drainage?'+new URLSearchParams({domain,occurrence:o.id})}>Saisir / consulter le drainage</Link>}<p>{date(o.planned_at)} · {o.confirmed_at?'Réalisée':o.cancelled_at?'Non réalisée':'À réaliser'}</p>{missing.map((r:any)=><p key={r.item} className="text-amber-700">À approvisionner : {r.product} — {waterFormat(r.missing)} {r.unit}</p>)}{o.cancelled_at?<p>Motif : {o.cancel_reason}</p>:o.confirmed_at?<details><summary>Réel et traçabilité</summary><p>{date(o.performed_at)} · {o.actual.notes}</p><p>Eau réelle : {waterFormat(o.actual.water_liters)} L</p>{o.actual.products.map((l:any)=><p key={l.stock_item_id}>{p.products.find((x:any)=>x.stock_item_id===l.stock_item_id)?.name} : {waterFormat(l.quantity)}</p>)}<p>{o.actual.deviation_reason}</p><p>Consommations consultables dans Stocks → Mouvements et Coûts. Prix absent : rapprochement requis.</p></details>:p.status==='approuvee'&&farm?.can_execute&&<div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>beginActual(o)}>Confirmer le réel</Button><Button variant="ghost" disabled={busy} onClick={()=>{const reason=window.prompt('Motif de non-réalisation (5 caractères minimum)');if(reason)void run(async()=>{await rpc('skip_cultural_occurrence',{p_id:o.id,p_reason:reason});await load()})}}>Non réalisée</Button></div>}</div>})}
   <Textarea aria-label="Commentaire de décision" placeholder="Motif requis pour refuser ou annuler" value={comment} onChange={e=>setComment(e.target.value)}/><div className="flex flex-wrap gap-2">{p.status==='brouillon'&&p.requested_by===user&&farm?.can_plan&&<Button disabled={busy} onClick={()=>action('submit')}>Soumettre</Button>}{p.can_review&&<><Button disabled={busy} onClick={()=>action('approve')}>Approuver niveau {p.current_level}</Button><Button disabled={busy} variant="ghost" onClick={()=>action('reject')}>Refuser</Button></>}{['brouillon','soumise','approuvee'].includes(p.status)&&(farm?.can_validate||(p.requested_by===user&&farm?.can_plan))&&<Button disabled={busy} variant="ghost" onClick={()=>action('cancel')}>Annuler le restant</Button>}{farm?.can_plan&&<Button variant="ghost" onClick={copy}>Copier / replanifier</Button>}</div>
   {p.status==='soumise'&&!p.can_review&&<p>En attente d’une autre personne habilitée au niveau {p.current_level}.</p>}<details><summary>Historique</summary>{p.audit.map((a:any)=><p key={a.id}>{date(a.created_at)} · {a.action} {a.level_number?`N${a.level_number}`:''} · {a.details.comment||''}</p>)}</details>{error&&<p role="alert" className="text-danger">{error}</p>}
  </div></Modal>}
  {p&&execution&&<Modal title="Confirmer l’intervention réelle" size="lg" onClose={()=>!busy&&setExecution('')}><div className="space-y-3"><fieldset disabled={busy||realFrozen} className="space-y-3 min-w-0"><label className="block">Date et heure réelles *<Input aria-label="Date réelle" {...fieldProps('date')} type="datetime-local" value={actual.performed_at} onChange={e=>{clearField('date');setActual({...actual,performed_at:e.target.value})}}/>{fieldError('date')}</label><label className="block">Eau réelle globale (L)<Input aria-label="Eau réelle" {...fieldProps('water')} inputMode="decimal" value={actual.water_liters} onChange={e=>{clearField('water');setActual({...actual,water_liters:e.target.value})}}/>{fieldError('water')}</label>
   <div className="rounded-xl border border-border bg-surface-input p-4 space-y-2"><strong>Impact de cette confirmation</strong><p>Entrepôt : {data.warehouses.find((w:any)=>w.id===p.warehouse_id)?.name||'Sans produit'}.</p><p className="text-sm">Seules les quantités réellement consommées seront sorties. Une préparation restant en bac ne doit pas être déclarée comme appliquée.</p><p className="text-sm">Imputation estimée des coûts par surface réelle confirmée, et non par volume mesuré dans chaque serre. Un prix absent ne sera pas assimilé à zéro.</p><ul className="text-sm">{p.targets.map((t:any)=>{let share='—';try{const sum=Object.values(areas).reduce((s,v)=>s+decimal(v),0);if(sum>0)share=waterFormat(100*decimal(areas[t.planting_id])/sum)+' %'}catch{}return <li key={t.planting_id}>{t.greenhouse} : {share} des coûts consommés</li>})}</ul></div>
   {p.products.length>0&&<label className="flex gap-2"><input type="checkbox" {...fieldProps('consumption')} checked={consumptionConfirmed} onChange={e=>{clearField('consumption');setConsumptionConfirmed(e.target.checked)}}/>Je confirme les quantités réellement consommées, hors solution restant en bac.{fieldError('consumption')}</label>}
   {p.targets.map((t:any)=><label key={t.planting_id} className="block">Surface réelle {t.greenhouse} (m²)<Input aria-label={`Réel ${t.greenhouse}`} {...fieldProps('area-'+t.planting_id)} inputMode="decimal" value={areas[t.planting_id]} onChange={e=>{clearField('area-'+t.planting_id);setAreas({...areas,[t.planting_id]:e.target.value})}}/>{fieldError('area-'+t.planting_id)}</label>)}
   <label><input type="checkbox" checked={manual} onChange={e=>{if(e.target.checked){try{setQuantities(Object.fromEntries(p.products.map((l:any)=>[l.stock_item_id,String(calculated(l))])))}catch{}}setManual(e.target.checked)}}/> Ajuster manuellement les quantités réellement consommées (justificatif requis si écart)</label>
   {p.products.map((l:any)=>{let q='';try{q=String(calculated(l))}catch{}return <label key={l.stock_item_id} className="block">{l.name} ({l.unit})<Input aria-label={`Quantité réelle ${l.name}`} {...fieldProps('quantity-'+l.stock_item_id)} disabled={!manual} inputMode="decimal" value={manual?quantities[l.stock_item_id]:q?waterFormat(Number(q)):''} onChange={e=>{clearField('quantity-'+l.stock_item_id);setQuantities({...quantities,[l.stock_item_id]:e.target.value})}}/>{fieldError('quantity-'+l.stock_item_id)}</label>})}
   {manual&&<label className="block">Justificatif des écarts<Textarea aria-label="Justificatif" {...fieldProps('reason')} value={actual.deviation_reason} onChange={e=>{clearField('reason');setActual({...actual,deviation_reason:e.target.value})}}/>{fieldError('reason')}</label>}<label className="block">Observation du réalisé *<Textarea aria-label="Observation" {...fieldProps('notes')} value={actual.notes} onChange={e=>{clearField('notes');setActual({...actual,notes:e.target.value})}}/>{fieldError('notes')}</label><label className="flex gap-2"><input type="checkbox" {...fieldProps('surfaces')} checked={actual.homogeneous} onChange={e=>{clearField('surfaces');setActual({...actual,homogeneous:e.target.checked})}}/>Je confirme la réalisation et la répartition homogène des produits selon les surfaces réelles indiquées. Le stock et les coûts seront mis à jour.{fieldError('surfaces')}</label></fieldset>{Object.keys(actualErrors).length>0&&<div role="alert" className="rounded-lg border border-danger/30 bg-danger/5 p-3"><strong>Champs à corriger</strong><ul className="mt-2 space-y-1">{Object.entries(actualErrors).map(([key,message])=><li key={key}><button type="button" className="text-left text-danger underline" onClick={()=>focusField(key)}>{message}</button></li>)}</ul></div>}{error&&<p role="alert" className="text-danger">{error}</p>}<Button disabled={busy} onClick={confirm}>{busy?'Traitement…':realFrozen?'Réessayer la même confirmation':'Confirmer les consommations'}</Button></div></Modal>}
 </div>
}
