'use client'
import { useEffect, useState, useCallback, useRef } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { StationReview } from '@/components/phyto/StationReview'
import { PageHeader } from '@/components/ui/PageHeader'
import { Select, Textarea } from '@/components/ui/Input'
import { ClipboardCheck, Bell, AlertCircle, CheckCircle2 } from 'lucide-react'
import { CulturalApprovalDetails } from '@/components/interventions/CulturalApprovalDetails'
import { IrrigationApprovalDetails } from '@/components/interventions/IrrigationApprovalDetails'
import { withDeadline } from '@/lib/withDeadline'

const labels:Record<string,string>={purchase_order:'Bon d’achat',stock_transfer:'Transfert de stock',treatment:'Traitement',stock_exit:'Sortie de stock',irrigation:'Programme d’irrigation',cultural:'Intervention culturale'}
const fieldLabels:Record<string,string>={quantity:'Quantité',planned_quantity:'Quantité prévue',dose:'Dose',dose_unit:'Unité de dose',unit:'Unité',unit_price:'Prix unitaire',line_total:'Total',item_description:'Article',product_name:'Produit',target_name:'Cible biologique',diagnosis:'Diagnostic',justification:'Justification',reason:'Motif',notes:'Notes',planned_at:'Date prévue',requested_for:'Date souhaitée',planned_date:'Date prévue',treated_area_m2:'Surface traitée (m²)',water_volume_liters:'Bouillie (L)',phi_days:'DAR (jours)',reentry_hours:'Délai de rentrée (h)',currency:'Devise',total_amount:'Montant total',order_date:'Date du bon',po_number:'Numéro',status:'Statut',reference:'Référence',label_confirmed:'Étiquette confirmée'}
function Fields({value}:{value:any}){return <dl className="grid grid-cols-1 gap-2 sm:grid-cols-2">{Object.entries(value||{}).filter(([k,v])=>fieldLabels[k]&&v!=null&&v!=='').map(([k,v])=><div key={k}><dt className="text-xs text-fg-tertiary">{fieldLabels[k]}</dt><dd className="break-words">{typeof v==='number'?v.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}):typeof v==='boolean'?(v?'Oui':'Non'):String(v)}</dd></div>)}</dl>}
export default function MobileApprovals(){
 const {user,switchDomain}=useAuth();const router=useRouter();const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(''),[filter,setFilter]=useState(''),[comments,setComments]=useState<Record<string,string>>({}),[online,setOnline]=useState(true)
 const [success,setSuccess]=useState('')
 const [stationRequest,setStationRequest]=useState<string|null>(null)
 const generation=useRef(0),loadedFor=useRef('')
 const visibleItems=loadedFor.current===user?.id?items:[]
 const load=useCallback(async()=>{const serial=++generation.current;if(!user){setItems([]);return}setBusy(true);setError('');try{const r=await withDeadline(signal=>supabase.rpc('mobile_approval_items').abortSignal(signal),20000,'Chargement trop long. Actualisez.');if(r.error)throw r.error;if(serial!==generation.current)return;loadedFor.current=user.id;setItems(r.data||[])}catch(e:any){if(serial===generation.current){setItems([]);setError(e.message||'Chargement impossible')}}finally{if(serial===generation.current)setBusy(false)}},[user])
 useEffect(()=>{setItems([]);void load();const timer=setInterval(load,45000);const connectivity=()=>setOnline(navigator.onLine);connectivity();window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);return()=>{generation.current++;clearInterval(timer);window.removeEventListener('online',connectivity);window.removeEventListener('offline',connectivity)}},[load])
 async function review(item:any,approve:boolean){if(!online||saving)return;setSuccess('');if(item.kind==='treatment'&&approve){setStationRequest(item.id);return}const key=item.kind+item.id;if(!online||saving)return;if(!approve&&!(comments[key]||'').trim()){setError('Renseignez le motif du refus dans la demande.');return}if(!approve&&['irrigation','cultural'].includes(item.kind)&&(comments[key]||'').trim().length<5){setError('Le motif du refus doit contenir au moins 5 caractères.');return}if(!window.confirm(`${approve?'Approuver':'Refuser'} ${item.kind==='irrigation'?'tout ce programme d’irrigation':'cette demande'} — ${item.company} — ${item.reference||item.process} ?`))return;setSaving(key);setError('');try{const r=await withDeadline(signal=>supabase.rpc('mobile_review',{p_kind:item.kind,p_id:item.id,p_level:item.level,p_approve:approve,p_comment:comments[key]||null}).abortSignal(signal),25000,'Réponse trop longue');if(r.error)throw r.error;setSuccess(`${item.reference||'La demande'} : ${approve?'approbation enregistrée':'refus enregistré'}.`);await load()}catch(e:any){setError((e.message||'Réponse inconnue')+' Actualisez avant de réessayer : la demande a peut-être été traitée.')}finally{setSaving('')}}
 const companies=Array.from(new Map(visibleItems.map(i=>[i.domain_id,i.company])).entries())
 const filteredItems=visibleItems.filter(i=>!filter||i.domain_id===filter)
 return <main className="mx-auto max-w-4xl space-y-5 pb-16">
 <PageHeader title="Mes validations" subtitle="Décisions en attente" icon={ClipboardCheck} description="Retrouvez les demandes qui nécessitent votre décision, selon vos habilitations." actions={<Link href="/parametres/mobile" className="btn btn-secondary"><Bell size={15}/>Réglages des notifications</Link>}/>
 {stationRequest&&<StationReview key={stationRequest} requestId={stationRequest} onClose={()=>setStationRequest(null)} onDone={()=>{setStationRequest(null);setSuccess('Décision enregistrée. La liste est actualisée.');void load()}}/>}
 {!online&&<div role="alert" className="flex gap-3 rounded-xl border border-warning bg-warning-dim p-4 text-fg-primary"><AlertCircle className="shrink-0" size={20}/><div><strong>Vous êtes hors ligne</strong><p className="mt-1 text-sm">Reconnectez-vous pour approuver ou refuser une demande. Aucune décision ne sera envoyée hors ligne.</p></div></div>}
 {error&&<div role="alert" className="flex gap-3 rounded-xl border border-danger bg-danger-dim p-4 text-fg-primary"><AlertCircle className="shrink-0 text-danger" size={20}/><div><strong>Une vérification est nécessaire</strong><p className="mt-1 break-words text-sm">{error}</p></div></div>}
 {success&&<div role="status" className="flex items-center gap-3 rounded-xl border border-border bg-success-dim p-4 text-sm text-fg-primary"><CheckCircle2 size={20} className="shrink-0 text-success"/>{success}</div>}
 <section className="card flex flex-wrap items-end gap-3 p-4"><label className="min-w-0 flex-1 text-xs text-fg-secondary">Société<Select aria-label="Société" value={filter} onChange={e=>setFilter(e.target.value)} className="mt-1.5"><option value="">Toutes mes sociétés</option>{companies.map(([id,name])=><option key={id} value={id}>{name}</option>)}</Select></label><button className="btn btn-secondary" disabled={busy||!!saving} onClick={load}>{busy?'Chargement…':'Actualiser'}</button><p role="status" className="w-full text-sm text-fg-tertiary">{busy?'Actualisation des demandes…':`${filteredItems.length} demande(s) à traiter`} · Toutes vos sociétés autorisées</p></section>
 {!busy&&!filteredItems.length&&!error&&<div className="card p-8 text-center"><CheckCircle2 size={30} className="mx-auto mb-3 text-success"/><h2 className="font-semibold">Aucune demande en attente</h2><p className="mt-2 text-sm text-fg-secondary">{filter?'Aucune demande pour cette société. Vous pouvez consulter toutes vos sociétés avec le filtre.':'Vous n’avez aucune demande à traiter avec vos habilitations actuelles.'}</p></div>}
 {filteredItems.map(item=>{const key=item.kind+item.id;return <article key={key} className="rounded-xl border border-border bg-surface-raised p-5 space-y-4 shadow-sm"><header className="border-b border-border pb-3"><p className="text-sm font-semibold text-brand">{item.company} · {labels[item.process]||item.process}</p><h2 className="font-bold text-lg">{item.reference||'Demande'}</h2><p className="text-sm">Niveau {item.level} / {item.levels} · {new Date(item.created_at).toLocaleString('fr-FR')}</p></header>{item.kind==='cultural'?<CulturalApprovalDetails entity={item.entity}/>:item.kind==='irrigation'?<IrrigationApprovalDetails entity={item.entity}/>:<Fields value={item.entity}/>}
 {!!item.lines?.length&&<details open><summary className="font-semibold">Articles / produits ({item.lines.length})</summary><div className="space-y-3 mt-2">{item.lines.map((line:any,index:number)=><div key={line.id||index} className="rounded-lg border border-border p-3"><Fields value={line}/></div>)}</div></details>}
 <div className="rounded-lg bg-surface-input p-3 text-sm space-y-1 text-fg-secondary"><p>Demandeur : {item.requester||'Non renseigné'}</p>{item.farm&&<p>Ferme : {item.farm}</p>}{item.supplier&&<p>Fournisseur : {item.supplier}</p>}{item.source_warehouse&&<p>Entrepôt source : {item.source_warehouse}</p>}{item.destination_warehouse&&<p>Entrepôt destinataire : {item.destination_warehouse}</p>}</div>
 <button onClick={async()=>{try{await switchDomain(item.domain_id);router.push(item.href)}catch{setError('Changement de société impossible')}}} className="inline-block underline text-brand">Ouvrir la fiche complète (pièces et contexte)</button>
 {!!item.history?.length&&<details><summary>Historique des décisions</summary>{item.history.map((h:any)=><p key={h.id} className="text-sm">N{h.level_number} · {h.decision} · {h.comment||'—'}</p>)}</details>}
 <label className="block text-sm">Commentaire (obligatoire pour refuser)<Textarea className="mt-2" value={comments[key]||''} onChange={e=>setComments({...comments,[key]:e.target.value})} maxLength={2000}/></label>
 <div className="grid grid-cols-2 gap-3"><button className="rounded bg-red-50 border border-red-300 text-red-900 p-3" disabled={!online||!!saving} onClick={()=>review(item,false)}>Refuser</button><button className="rounded bg-green-800 text-white p-3" disabled={!online||!!saving} onClick={()=>review(item,true)}>{saving===key?'Traitement…':'Approuver'}</button></div></article>})}
 </main>
}
