'use client'
import { useEffect, useState, useCallback, useRef } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { StationReview } from '@/components/phyto/StationReview'
import { MobileSetup } from '@/components/mobile/MobileSetup'

const labels:Record<string,string>={purchase_order:'Bon d’achat',stock_transfer:'Transfert de stock',treatment:'Traitement',stock_exit:'Sortie de stock'}
const fieldLabels:Record<string,string>={quantity:'Quantité',planned_quantity:'Quantité prévue',dose:'Dose',dose_unit:'Unité de dose',unit:'Unité',unit_price:'Prix unitaire',line_total:'Total',item_description:'Article',product_name:'Produit',target_name:'Cible biologique',diagnosis:'Diagnostic',justification:'Justification',reason:'Motif',notes:'Notes',planned_at:'Date prévue',requested_for:'Date souhaitée',planned_date:'Date prévue',treated_area_m2:'Surface traitée (m²)',water_volume_liters:'Bouillie (L)',phi_days:'DAR (jours)',reentry_hours:'Délai de rentrée (h)',currency:'Devise',total_amount:'Montant total',order_date:'Date du bon',po_number:'Numéro',status:'Statut',reference:'Référence',label_confirmed:'Étiquette confirmée'}
function Fields({value}:{value:any}){return <dl className="grid grid-cols-1 gap-2 sm:grid-cols-2">{Object.entries(value||{}).filter(([k,v])=>fieldLabels[k]&&v!=null&&v!=='').map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{fieldLabels[k]}</dt><dd className="break-words">{typeof v==='number'?v.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}):typeof v==='boolean'?(v?'Oui':'Non'):String(v)}</dd></div>)}</dl>}
export default function MobileApprovals(){
 const {user,switchDomain,isAdmin,isPlatformAdmin}=useAuth();const router=useRouter();const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(''),[filter,setFilter]=useState(''),[comments,setComments]=useState<Record<string,string>>({}),[online,setOnline]=useState(true)
 const [stationRequest,setStationRequest]=useState<string|null>(null)
 const generation=useRef(0),loadedFor=useRef('')
 const visibleItems=loadedFor.current===user?.id?items:[]
 const load=useCallback(async()=>{const serial=++generation.current;if(!user){setItems([]);return}setBusy(true);setError('');try{const r=await supabase.rpc('mobile_approval_items').abortSignal(AbortSignal.timeout(20000));if(r.error)throw r.error;if(serial!==generation.current)return;loadedFor.current=user.id;setItems(r.data||[])}catch(e:any){if(serial===generation.current){setItems([]);setError(e.message||'Chargement impossible')}}finally{if(serial===generation.current)setBusy(false)}},[user])
 useEffect(()=>{setItems([]);void load();const timer=setInterval(load,45000);const connectivity=()=>setOnline(navigator.onLine);connectivity();window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);return()=>{generation.current++;clearInterval(timer);window.removeEventListener('online',connectivity);window.removeEventListener('offline',connectivity)}},[load])
 async function review(item:any,approve:boolean){if(item.kind==='treatment'&&approve){setStationRequest(item.id);return}const key=item.kind+item.id;if(!online||saving)return;if(!approve&&!(comments[key]||'').trim()){setError('Renseignez le motif du refus dans la demande.');return}if(!window.confirm(`${approve?'Approuver':'Refuser'} cette demande — ${item.company} — ${item.reference||item.process} ?`))return;setSaving(key);setError('');try{const r=await supabase.rpc('mobile_review',{p_kind:item.kind,p_id:item.id,p_level:item.level,p_approve:approve,p_comment:comments[key]||null}).abortSignal(AbortSignal.timeout(25000));if(r.error)throw r.error;await load()}catch(e:any){setError((e.message||'Réponse inconnue')+' Actualisez avant de réessayer : la demande a peut-être été traitée.')}finally{setSaving('')}}
 const companies=Array.from(new Map(visibleItems.map(i=>[i.domain_id,i.company])).entries())
 return <main className="mx-auto max-w-3xl space-y-4 pb-16"><h1 className="text-2xl font-bold">Mes validations</h1><p>Demandes accessibles selon vos habilitations, toutes vos sociétés. La décision reste contrôlée par le serveur.</p><MobileSetup/>{stationRequest&&<StationReview key={stationRequest} requestId={stationRequest} onClose={()=>setStationRequest(null)} onDone={()=>{setStationRequest(null);void load()}}/>}
 {(isAdmin||isPlatformAdmin)&&<Link href="/validations/parametres" className="inline-block underline">Paramétrer les notifications et rappels</Link>}
 {!online&&<p role="alert" className="bg-amber-100 p-3">Hors ligne : validation désactivée.</p>}{error&&<p role="alert" className="bg-red-50 text-red-800 p-3 rounded">{error}</p>}
 <div className="flex gap-2"><select aria-label="Société" value={filter} onChange={e=>setFilter(e.target.value)} className="min-w-0 flex-1 border rounded p-3 bg-white text-slate-900"><option value="">Toutes mes sociétés</option>{companies.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button className="border rounded p-3" disabled={busy||!!saving} onClick={load}>{busy?'Chargement…':'Actualiser'}</button></div>
 {!busy&&!visibleItems.length&&!error&&<p className="rounded border p-5">Aucune demande à valider avec vos habilitations actuelles.</p>}
 {visibleItems.filter(i=>!filter||i.domain_id===filter).map(item=>{const key=item.kind+item.id;return <article key={key} className="rounded-xl border bg-white text-slate-900 p-4 space-y-3 shadow-sm"><header><p className="text-sm font-semibold text-green-800">{item.company} · {labels[item.process]||item.process}</p><h2 className="font-bold text-lg">{item.reference||'Demande'}</h2><p className="text-sm">Niveau {item.level} / {item.levels} · {new Date(item.created_at).toLocaleString('fr-FR')}</p></header><Fields value={item.entity}/>
 {!!item.lines?.length&&<details open><summary className="font-semibold">Articles / produits ({item.lines.length})</summary><div className="space-y-3 mt-2">{item.lines.map((line:any,index:number)=><div key={line.id||index} className="border rounded p-3"><Fields value={line}/></div>)}</div></details>}
 <div className="text-sm space-y-1"><p>Demandeur : {item.requester||'Non renseigné'}</p>{item.farm&&<p>Ferme : {item.farm}</p>}{item.supplier&&<p>Fournisseur : {item.supplier}</p>}{item.source_warehouse&&<p>Entrepôt source : {item.source_warehouse}</p>}{item.destination_warehouse&&<p>Entrepôt destinataire : {item.destination_warehouse}</p>}</div>
 <button onClick={async()=>{try{await switchDomain(item.domain_id);router.push(item.href)}catch{setError('Changement de société impossible')}}} className="inline-block underline text-green-800">Ouvrir la fiche complète (pièces et contexte)</button>
 {!!item.history?.length&&<details><summary>Historique des décisions</summary>{item.history.map((h:any)=><p key={h.id} className="text-sm">N{h.level_number} · {h.decision} · {h.comment||'—'}</p>)}</details>}
 <label className="block text-sm">Commentaire (obligatoire pour refuser)<textarea className="block w-full rounded border p-3 mt-1" value={comments[key]||''} onChange={e=>setComments({...comments,[key]:e.target.value})} maxLength={2000}/></label>
 <div className="grid grid-cols-2 gap-3"><button className="rounded bg-red-50 border border-red-300 text-red-900 p-3" disabled={!online||!!saving} onClick={()=>review(item,false)}>Refuser</button><button className="rounded bg-green-800 text-white p-3" disabled={!online||!!saving} onClick={()=>review(item,true)}>{saving===key?'Traitement…':'Approuver'}</button></div></article>})}
 </main>
}
