import type {PlanGraphic} from '@/lib/drawioFarmPlan'
import {farmPlanPalette} from '@/lib/farmPlanPalette'
const control='rounded-md border border-border bg-surface-raised p-2 text-sm'
export function GraphicEditor({elements,selected,disabled,onSelect,onAdd,onUpdate,onDuplicate,onRemove,onLayer}:{elements:PlanGraphic[];selected:string;disabled:boolean;onSelect:(id:string)=>void;onAdd:(kind:string)=>void;onUpdate:(patch:Partial<PlanGraphic>)=>void;onDuplicate:()=>void;onRemove:()=>void;onLayer:(front:boolean)=>void}){
 const e=elements.find(e=>e.id===selected)
 return <fieldset disabled={disabled} className="space-y-3 min-w-0"><legend className="font-semibold mb-2">Composants du plan</legend><p className="text-xs text-fg-secondary">Palette inspirée du plan général de la ferme 114. Les composants sont graphiques ; les serres restent liées au référentiel.</p>
 <details open><summary className="cursor-pointer">Ajouter un composant</summary><div className="grid grid-cols-2 gap-2 mt-2 max-h-80 overflow-y-auto pr-1">{farmPlanPalette.map(p=><button type="button" key={p[0]} className={`${control} text-left`} disabled={elements.length>=1000} onClick={()=>onAdd(p[0])}><span className="inline-block w-3 h-3 rounded mr-1 border" style={{background:p[2]==='none'?'white':p[2]}}/>{p[1]}</button>)}</div></details>
 <label className="block text-sm">Composant sélectionné<select className={`${control} w-full`} aria-label="Composant sélectionné" value={selected} onChange={e=>onSelect(e.target.value)}><option value="">Choisir sur le plan ou dans la liste</option>{elements.map((e,i)=><option key={e.id} value={e.id}>{i+1}. {e.label||e.kind}</option>)}</select></label>
 {e&&<div className="space-y-2 border-t pt-3"><label className="block">Libellé<input className={`${control} w-full`} aria-label="Libellé du composant" maxLength={500} value={e.label} onChange={v=>onUpdate({label:v.target.value})}/></label>
 {(['x','y','width','height','rotation','fontSize'] as const).map((k,i)=><label className="flex justify-between gap-2 text-sm items-center" key={k}>{['Position X','Position Y','Largeur','Hauteur','Rotation (°)','Taille du texte'][i]}<input className={`${control} w-24`} aria-label={`Composant ${k}`} type="number" value={Math.round(e[k])} onChange={v=>{if(v.target.value!=='')onUpdate({[k]:Number(v.target.value)})}}/></label>)}
 {(['fill','stroke','fontColor'] as const).map((k,i)=><div key={k} className="flex justify-between items-center text-sm"><label>{['Fond','Contour','Texte'][i]} <input type="color" aria-label={`Couleur ${k}`} value={e[k]==='none'?'#ffffff':e[k]} onChange={v=>onUpdate({[k]:v.target.value})}/></label>{k!=='fontColor'&&<button className={control} onClick={()=>onUpdate({[k]:'none'})}>Transparent</button>}</div>)}
 <div className="flex flex-wrap gap-2"><button className={control} disabled={elements.length>=1000} onClick={onDuplicate}>Dupliquer</button><button className={control} onClick={()=>onLayer(false)}>Reculer au fond</button><button className={control} onClick={()=>onLayer(true)}>Devant les composants</button><button className={`${control} text-danger`} onClick={onRemove}>Supprimer le composant</button></div><p className="text-xs text-fg-secondary">Glissez le composant sur le plan. Les serres restent au-dessus des composants et leur surface officielle ne change pas.</p></div>}
 </fieldset>
}
