'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {useAuth} from '@/lib/auth'
import {supabase} from '@/lib/supabase'
const processes:Record<string,string>={purchase_order:'Bons d’achat',stock_transfer:'Transferts',treatment:'Traitements',stock_exit:'Sorties de stock',irrigation:'Programmes d’irrigation',cultural:'Interventions culturales'}
export default function NotificationSettings(){const {activeDomain,isAdmin,isPlatformAdmin}=useAuth();const domain=activeDomain?.domain_id;const [rules,setRules]=useState<Record<string,any>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setRules({});if(!domain)return;let stopped=false;supabase.from('mobile_notification_rules').select('*').eq('domain_id',domain).then(r=>{if(stopped)return;if(r.error)setMessage(r.error.message);else setRules(Object.fromEntries((r.data||[]).map(x=>[x.process,x])))});return()=>{stopped=true}},[domain])
 if(!isAdmin&&!isPlatformAdmin)return <p>Administration de la société requise.</p>
 return <main className="mx-auto max-w-2xl space-y-4"><Link href="/validations">← Mes validations</Link><h1 className="text-2xl font-bold">Notifications de validation</h1><p>Société sélectionnée dans la barre supérieure. Ces réglages n’activent ni ne désactivent la validation métier ; ils contrôlent uniquement les notifications et leurs rappels.</p><p className="rounded border border-amber-300 bg-amber-50 p-3 text-amber-900">Irrigation / interventions culturales : activer les envois seulement après application de 134 / 135C et publication de l’écran mobile mis à jour. Les canaux push/Telegram doivent être activés par chaque destinataire.</p>{Object.entries(processes).map(([process,label])=>{const r=rules[process]||{enabled:!['irrigation','cultural'].includes(process),reminder_hours:24};return <div key={process} className="border rounded p-4 space-y-2"><h2 className="font-semibold">{label}</h2><label className="block"><input type="checkbox" checked={r.enabled} onChange={e=>setRules({...rules,[process]:{...r,enabled:e.target.checked}})}/> Notifications activées</label><label>Rappel après (heures) <input className="border p-2 w-24 rounded text-slate-900" type="number" min={1} max={720} value={r.reminder_hours} onChange={e=>setRules({...rules,[process]:{...r,reminder_hours:e.target.value}})}/></label></div>})}
 <button className="rounded bg-green-800 text-white p-3" disabled={busy||!domain} onClick={async()=>{setBusy(true);setMessage('');try{const rows=Object.keys(processes).map(process=>({domain_id:domain,process,enabled:rules[process]?.enabled??(!['irrigation','cultural'].includes(process)),reminder_hours:Number(rules[process]?.reminder_hours??24)}));if(rows.some(r=>!Number.isInteger(r.reminder_hours)||r.reminder_hours<1||r.reminder_hours>720))throw Error('Délai entier entre 1 et 720 heures requis');const r=await supabase.from('mobile_notification_rules').upsert(rows).abortSignal(AbortSignal.timeout(20000));if(r.error)throw r.error;setMessage('Paramètres enregistrés')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}}>{busy?'Enregistrement…':'Enregistrer'}</button><p role="status">{message}</p><p>Les rappels nécessitent l’activation du service d’envoi planifié sur le serveur. Aucune escalade ne donne automatiquement de nouveaux droits à un utilisateur.</p></main>
}
