'use client'
import { useEffect,useState } from 'react'
import { toast } from 'sonner'
import { Save,ShieldCheck } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { PageHeader } from '@/components/ui/PageHeader'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Badge } from '@/components/ui/Badge'
import { EmptyState } from '@/components/ui/EmptyState'
import { Input,Select } from '@/components/ui/Input'
import { DataTable,THead,TR,TH,TD } from '@/components/ui/DataTable'

const PROCESS:Record<string,string>={purchase_order:"Bon d’achat",direct_purchase:'Achat direct',stock_exit:'Sortie de stock',stock_adjustment:'Ajustement de stock',treatment:'Traitement phytosanitaire',phyto_receipt:'Réception phytosanitaire',stock_transfer:'Transfert entre entrepôts'}
export default function ValidationsPage(){
 const {activeDomain,isAdmin,isPlatformAdmin}=useAuth();const [items,setItems]=useState<any[]>([]);const [capabilities,setCapabilities]=useState<any[]>([]);const [levels,setLevels]=useState<Record<string,any[]>>({});const [dirty,setDirty]=useState<Set<string>>(new Set());const [saving,setSaving]=useState(false)
 const load=async()=>{if(!activeDomain)return;const [p,c,l]=await Promise.all([supabase.from('approval_policies').select('*').eq('domain_id',activeDomain.domain_id).order('priority'),supabase.from('business_capabilities').select('id,code,name,process_code').eq('is_active',true).eq('is_sensitive',true).order('name'),supabase.from('approval_policy_levels').select('*')]);if(p.error&&!p.error.message.includes('approval_policies'))toast.error(p.error.message);if(c.error&&!c.error.message.includes('business_capabilities'))toast.error(c.error.message);setItems(p.data||[]);setCapabilities(c.data||[]);setLevels((l.data||[]).reduce((out:Record<string,any[]>,row:any)=>{(out[row.policy_id]??=[]).push(row);out[row.policy_id].sort((a,b)=>a.level_number-b.level_number);return out},{}));setDirty(new Set())}
 useEffect(()=>{load()},[activeDomain?.domain_id]);const change=(id:string,key:string,value:any)=>{setItems(v=>v.map(x=>x.id===id?{...x,[key]:value}:x));setDirty(v=>new Set(v).add(id))}
 const levelChange=(policy:any,levelNumber:number,capabilityId:string)=>{setLevels(current=>{const rows=[...(current[policy.id]||[])];const existing=rows.find(x=>x.level_number===levelNumber);if(existing)existing.required_capability_id=capabilityId;else rows.push({policy_id:policy.id,level_number:levelNumber,required_capability_id:capabilityId,responsible_role_id:policy.responsible_role_id||null,name:`Niveau ${levelNumber}`});return {...current,[policy.id]:rows.sort((a,b)=>a.level_number-b.level_number)}});setDirty(v=>new Set(v).add(policy.id))}
 const save=async()=>{setSaving(true);try{for(const p of items.filter(x=>dirty.has(x.id))){const {error}=await supabase.from('approval_policies').update({validation_enabled:p.validation_enabled,approval_levels:Number(p.approval_levels),amount_threshold:p.amount_threshold===''?null:Number(p.amount_threshold),updated_at:new Date().toISOString()}).eq('id',p.id);if(error)throw error;const rows=Array.from({length:Number(p.approval_levels)},(_,index)=>{const level=index+1;const current=(levels[p.id]||[]).find(x=>x.level_number===level);return {level_number:level,required_capability_id:current?.required_capability_id||capabilities.find(c=>c.process_code===p.process_code)?.id||'',responsible_role_id:current?.responsible_role_id||p.responsible_role_id||null,name:`Niveau ${level}`}});const synced=await supabase.rpc('sync_approval_policy_levels',{p_policy:p.id,p_levels:rows});if(synced.error)throw synced.error}toast.success('Circuits de validation enregistrés');await load()}catch(e:any){toast.error(e.message)}finally{setSaving(false)}}
 if(!isAdmin&&!isPlatformAdmin)return <EmptyState icon={ShieldCheck} title="Accès réservé à l’administrateur du domaine"/>
 return <div><PageHeader title="Circuits de validation" subtitle="Paramétrage par société" icon={ShieldCheck} iconColor="#8b5cf6" description="Chaque niveau exige une habilitation. Le demandeur ne peut jamais valider sa propre demande." actions={<Button onClick={save} disabled={!dirty.size||saving}><Save size={14}/>{saving?'Enregistrement…':'Enregistrer'}</Button>}/><Card padding="none"><DataTable minWidth={1100}><THead><TR><TH>Processus</TH><TH>Type</TH><TH>Validation</TH><TH>Niveaux et habilitations</TH><TH>Seuil minimum</TH><TH>État</TH></TR></THead><tbody>{items.map(p=><TR key={p.id}><TD className="font-display font-semibold">{PROCESS[p.process_code]||p.name}</TD><TD mono>{p.operation_type}</TD><TD><label className="flex items-center gap-sm"><input type="checkbox" checked={p.validation_enabled} onChange={e=>change(p.id,'validation_enabled',e.target.checked)}/><span>{p.validation_enabled?'Activée':'Désactivée'}</span></label></TD><TD><div className="space-y-xs"><Select value={String(p.approval_levels)} onChange={e=>change(p.id,'approval_levels',Number(e.target.value))} disabled={!p.validation_enabled}><option value="1">1 niveau</option><option value="2">2 niveaux</option><option value="3">3 niveaux</option></Select>{Array.from({length:Number(p.approval_levels)},(_,index)=>{const n=index+1;const row=(levels[p.id]||[]).find(x=>x.level_number===n);return <div key={n} className="flex items-center gap-xs"><span className="font-mono text-caption whitespace-nowrap">N{n}</span><Select value={row?.required_capability_id||''} onChange={e=>levelChange(p,n,e.target.value)} disabled={!p.validation_enabled}><option value="">— Habilitation —</option>{capabilities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></div>})}</div></TD><TD><Input type="number" min="0" value={p.amount_threshold??''} onChange={e=>change(p.id,'amount_threshold',e.target.value)} placeholder="Tous montants" disabled={!p.validation_enabled}/></TD><TD>{dirty.has(p.id)?<Badge variant="warning">Modifié</Badge>:<Badge variant={p.validation_enabled?'success':'default'}>{p.validation_enabled?'Contrôlé':'Automatique'}</Badge>}</TD></TR>)}</tbody></DataTable>{items.length===0&&<EmptyState icon={ShieldCheck} title="Aucune règle" description="Appliquez les migrations 082 puis 086."/>}</Card></div>
}
