import {describe,it,expect} from 'vitest'
import {production360,activity360,defaultAgroCampaign} from './agronomy360'
const gs=[{id:'g',farm_id:'f',code:'S1',name:'Serre',total_area:100},{id:'other',farm_id:'other',code:'S2',name:'Autre',total_area:200}]
const p={id:'p',greenhouse_id:'g',variety_id:'v',planted_area:100,planting_date:'2026-01-01',harvest_start_date:'2026-02-01',harvest_end_date:'2026-12-01',first_harvest_date:null,last_harvest_date:null,status:'en_cours',target_total_production:1000,target_yield_per_m2:null}
describe('Agronomie 360',()=>{
 it('selects active campaign before newer planned campaigns',()=>{expect(defaultAgroCampaign([{id:'planned',status:'planification',preparation_start:'2027-01-01'},{id:'active',status:'en_cours',preparation_start:'2026-01-01'}],'2026-09-18').id).toBe('active')})
 it('handles multiple active campaigns deterministically and explains fallback',()=>{expect(defaultAgroCampaign([{id:'a',status:'en_cours',preparation_start:'2025-01-01'},{id:'b',status:'en_cours',preparation_start:'2026-01-01'}],'2026-09-18').id).toBe('b');expect(defaultAgroCampaign([{id:'closed',status:'terminee',preparation_start:'2025-01-01'}],'2026-09-18').reason).toContain('Aucune campagne en cours');expect(defaultAgroCampaign([],'2026-09-18').id).toBe('')})
 it('filters scope and calculates weighted production',()=>{const s=production360([p],[{id:'h',campaign_planting_id:'p',harvest_date:'2026-03-01',total_qty:200},{id:'x',campaign_planting_id:'outside',harvest_date:'2026-03-01',total_qty:9999}],gs,'f','2026-03-02',7);expect(s.kg).toBe(200);expect(s.yield).toBe(2);expect(s.progress).toBe(20);expect(s.gs).toHaveLength(1)})
 it('does not invent targets or yield on empty area',()=>{const s=production360([{...p,planted_area:0,target_total_production:null}],[],gs,'f','2026-03-01',7);expect(s.target).toBeNull();expect(s.yield).toBeNull()})
 it('flags harvest silence only during an open expected window',()=>{expect(production360([p],[],gs,'f','2026-03-01',7).missingHarvest).toHaveLength(1);expect(production360([{...p,status:'terminee'}],[],gs,'f','2026-03-01',7).missingHarvest).toHaveLength(0);expect(production360([p],[],gs,'f','2026-01-10',7).missingHarvest).toHaveLength(0)})
 it('counts shared activities once and excludes closed activities from delays',()=>{const base={id:'a',family:'Phyto',name:'QA',farms:['f','other'],planned:'2026-03-01T10:00:00Z',actual:null,status:'approuvee',done:false,closed:false,water:null,href:'/'};const s=activity360([base,{...base,id:'b',closed:true,done:true,water:100}], 'f',Date.parse('2026-03-02'),15);expect(s.late).toHaveLength(1);expect(s.scoped).toHaveLength(2);expect(s.water).toBe(100);expect(activity360([base],'unknown',Date.now(),15).scoped).toHaveLength(0)})
})
