'use client'

import {useCallback,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,CheckCheck,CheckCircle2,Download,FileSearch,Pencil,RefreshCw,ShieldCheck} from 'lucide-react'
import {toast} from 'sonner'
import {useAuth} from '@/lib/auth'
import {supabase} from '@/lib/supabase'
import {Badge} from '@/components/ui/Badge'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {DataTable,TD,TH,THead,TR} from '@/components/ui/DataTable'
import {Field,Input,Select,Textarea} from '@/components/ui/Input'
import {Modal,ModalFooter} from '@/components/ui/Modal'

type PositiveList={id:string;version:string;document_code:string|null;document_date:string|null;source_file_name:string;source_file_path:string|null;status:string;imported_at:string;activated_at:string|null}
type Entry={id:string;commercial_name:string;target_label:string;active_substances:string|null;phi_days:number|null;dose_text:string|null;treatment_mode:string|null;eu_uk_mrl_text:string|null;swiss_mrl_text:string|null;review_status:string;comparison_status:string;product_id:string|null;target_id:string|null;source_page:number|null}
type Diff='nouveau'|'identique'|'modifie'|'retire'

const normalize=(v?:string|null)=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')
const key=(e:Entry)=>`${normalize(e.commercial_name)}::${normalize(e.target_label)}`
const statusVariant=(status:string)=>status==='active'?'success':status==='a_controler'?'warning':status==='rejetee'?'danger':'default'
const diffVariant=(status:Diff)=>status==='nouveau'?'success':status==='modifie'?'warning':status==='retire'?'danger':'default'

export default function PositiveListsPage(){
  const {activeDomain}=useAuth()
  const [lists,setLists]=useState<PositiveList[]>([]),[selectedId,setSelectedId]=useState(''),[entries,setEntries]=useState<Entry[]>([]),[previous,setPrevious]=useState<Entry[]>([])
  const [products,setProducts]=useState<any[]>([]),[targets,setTargets]=useState<any[]>([]),[editing,setEditing]=useState<Entry|null>(null),[busy,setBusy]=useState(false),[filter,setFilter]=useState('tous')
  const selected=lists.find(l=>l.id===selectedId)

  const loadLists=useCallback(async()=>{if(!activeDomain)return;const {data,error}=await supabase.from('phyto_positive_lists').select('*').eq('domain_id',activeDomain.domain_id).order('imported_at',{ascending:false});if(error){toast.error(error.message);return}const rows=(data||[]) as PositiveList[];setLists(rows);setSelectedId(current=>rows.some(x=>x.id===current)?current:(rows.find(x=>x.status==='a_controler')||rows[0])?.id||'')},[activeDomain?.domain_id])
  useEffect(()=>{loadLists()},[loadLists])
  useEffect(()=>{if(!activeDomain)return;Promise.all([supabase.from('plant_protection_products').select('id,commercial_name').eq('domain_id',activeDomain.domain_id).order('commercial_name'),supabase.from('phyto_targets').select('id,canonical_name').eq('is_active',true).order('canonical_name')]).then(([p,t])=>{setProducts(p.data||[]);setTargets(t.data||[])})},[activeDomain?.domain_id])
  const loadEntries=useCallback(async()=>{if(!selectedId||!activeDomain)return;const active=lists.find(l=>l.status==='active'&&l.id!==selectedId);const [current,old]=await Promise.all([supabase.from('phyto_positive_list_entries').select('*').eq('list_id',selectedId).order('source_row'),active?supabase.from('phyto_positive_list_entries').select('*').eq('list_id',active.id).eq('review_status','valide'):Promise.resolve({data:[],error:null})]);if(current.error){toast.error(current.error.message);return}setEntries((current.data||[]) as Entry[]);setPrevious((old.data||[]) as Entry[])},[selectedId,activeDomain?.domain_id,lists])
  useEffect(()=>{loadEntries()},[loadEntries])

  const diffById=useMemo(()=>{const old=new Map(previous.map(e=>[key(e),e]));return new Map(entries.map(e=>{const before=old.get(key(e));if(!before)return[e.id,'nouveau' as Diff];const same=['active_substances','phi_days','dose_text','treatment_mode','eu_uk_mrl_text','swiss_mrl_text'].every(k=>String((before as any)[k]??'')===String((e as any)[k]??''));return[e.id,same?'identique':'modifie']}))},[entries,previous])
  const removed=useMemo(()=>{const current=new Set(entries.map(key));return previous.filter(e=>!current.has(key(e))).map(e=>({...e,comparison_status:'retire'}))},[entries,previous])
  const visible=useMemo(()=>{const all=[...entries,...removed];return filter==='tous'?all:all.filter(e=>(e.comparison_status==='retire'?'retire':diffById.get(e.id))===filter||e.review_status===filter)},[entries,removed,filter,diffById])
  const counts=useMemo(()=>({pending:entries.filter(e=>e.review_status==='a_controler').length,valid:entries.filter(e=>e.review_status==='valide').length,rejected:entries.filter(e=>e.review_status==='rejete').length,unlinked:entries.filter(e=>e.review_status==='valide'&&(!e.product_id||!e.target_id)).length}),[entries])

  const saveEntry=async()=>{if(!editing)return;setBusy(true);const selectedTarget=targets.find(target=>target.id===editing.target_id);const payload={commercial_name:editing.commercial_name,target_label:selectedTarget?.canonical_name||editing.target_label,active_substances:editing.active_substances||null,phi_days:editing.phi_days,dose_text:editing.dose_text||null,treatment_mode:editing.treatment_mode||null,eu_uk_mrl_text:editing.eu_uk_mrl_text||null,swiss_mrl_text:editing.swiss_mrl_text||null,product_id:editing.product_id||null,target_id:editing.target_id||null,review_status:editing.review_status};const {data,error}=await supabase.from('phyto_positive_list_entries').update(payload).eq('id',editing.id).select('id,target_id,target_label').maybeSingle();setBusy(false);if(error)toast.error(error.message);else if(!data)toast.error("La ligne n'a pas été modifiée. Vérifiez vos droits sur ce client / cette société.");else{toast.success(`Ligne enregistrée — cible : ${data.target_label}`);setEditing(null);await loadEntries()}}
  const validateAll=async()=>{const pending=entries.filter(e=>e.review_status==='a_controler');if(!pending.length){toast.info('Aucune ligne en attente');return}if(!confirm(`Valider ${pending.length} ligne(s), créer les produits et cibles manquants, puis les relier au référentiel ?`))return;setBusy(true);const {data,error}=await supabase.rpc('validate_positive_list_globally',{p_list_id:selectedId});setBusy(false);if(error){toast.error(error.message);return}await loadEntries();const result=data as any;toast.success(`${result.rows_validated} ligne(s) validée(s) · ${result.products_created} produit(s) créé(s) · ${result.targets_created} cible(s) créée(s)`,{description:result.uses_pending?`${result.uses_pending} usage(s) restent à compléter et vérifier ONSSA.`:`${result.uses_created} usage(s) provisoire(s) créé(s).`})}
  const activate=async()=>{if(!selected)return;if(!confirm(`Activer la version ${selected.version} et remplacer la liste actuellement active ?`))return;setBusy(true);const {error}=await supabase.rpc('activate_phyto_positive_list',{p_list_id:selected.id});setBusy(false);if(error)toast.error(error.message);else{toast.success('Liste positive activée');await loadLists()}}
  const download=async()=>{if(!selected?.source_file_path)return;const {data,error}=await supabase.storage.from('phyto-positive-lists').createSignedUrl(selected.source_file_path,60);if(error)toast.error(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')}

  return <div className="space-y-md">
    <Link href={selected?'/stocks/preparation-phyto?list='+selected.id:'/stocks/preparation-phyto'}><Button variant="secondary">PRÉPARER LES ARTICLES DE STOCK</Button></Link>
    <div className="flex items-center justify-between gap-md"><div><Link href="/agronomie/produits"><ArrowLeft size={12}/> Produits phytosanitaires</Link><h1 className="text-heading font-bold mt-sm">Contrôle des listes positives</h1><p className="text-body-sm text-fg-tertiary">Historique, rapprochement avec le référentiel et activation par client / société.</p></div><Link href="/agronomie/produits/import"><Button>IMPORTER UNE LISTE</Button></Link></div>
    <Card><div className="grid grid-cols-1 lg:grid-cols-[1fr_auto] gap-md items-end"><Field label="Version à contrôler"><Select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Aucune liste importée</option>{lists.map(l=><option key={l.id} value={l.id}>Version {l.version} — {l.status.replace('_',' ')} — {l.document_date||new Date(l.imported_at).toLocaleDateString('fr-FR')}</option>)}</Select></Field><div className="flex gap-xs"><Button variant="ghost" onClick={loadEntries} disabled={!selectedId}><RefreshCw size={14}/> Actualiser</Button><Button variant="ghost" onClick={download} disabled={!selected?.source_file_path}><Download size={14}/> Source</Button></div></div>{selected&&<div className="flex flex-wrap gap-xs mt-md"><Badge variant={statusVariant(selected.status)}>{selected.status.replace('_',' ')}</Badge><span className="text-caption text-fg-tertiary">{selected.document_code||'Sans code'} · {selected.source_file_name}</span></div>}</Card>
    {selected&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-sm"><Card padding="sm"><div className="text-caption text-fg-tertiary">À contrôler</div><div className="text-heading font-bold text-warning">{counts.pending}</div></Card><Card padding="sm"><div className="text-caption text-fg-tertiary">Validées</div><div className="text-heading font-bold text-success">{counts.valid}</div></Card><Card padding="sm"><div className="text-caption text-fg-tertiary">Rejetées</div><div className="text-heading font-bold text-danger">{counts.rejected}</div></Card><Card padding="sm"><div className="text-caption text-fg-tertiary">Validées non reliées</div><div className="text-heading font-bold text-warning">{counts.unlinked}</div></Card></div>
    <div className="flex flex-wrap justify-between gap-sm"><div className="flex gap-xs"><Select value={filter} onChange={e=>setFilter(e.target.value)} className="w-48"><option value="tous">Toutes les lignes</option><option value="a_controler">À contrôler</option><option value="nouveau">Nouvelles</option><option value="modifie">Modifiées</option><option value="retire">Retirées</option><option value="rejete">Rejetées</option></Select></div>{selected.status!=='active'&&selected.status!=='remplacee'&&<div className="flex flex-wrap gap-xs"><Button variant="secondary" onClick={validateAll} loading={busy} disabled={counts.pending===0}><CheckCheck size={14}/> VALIDER GLOBALEMENT</Button><Button onClick={activate} loading={busy} disabled={counts.pending>0||counts.unlinked>0}><ShieldCheck size={14}/> ACTIVER CETTE VERSION</Button></div>}</div>
    <Card padding="none">{visible.length===0?<div className="p-xl text-center text-fg-tertiary"><FileSearch className="mx-auto mb-sm"/>Aucune ligne pour ce filtre.</div>:<DataTable minWidth={1200}><THead><TR><TH>Écart</TH><TH>Contrôle</TH><TH>Produit</TH><TH>Cible</TH><TH>Substance</TH><TH>DAR</TH><TH>Dose</TH><TH>LMR EU/UK</TH><TH>Page</TH><TH></TH></TR></THead><tbody>{visible.map(e=>{const isRemoved=e.comparison_status==='retire';const diff=(isRemoved?'retire':diffById.get(e.id)||e.comparison_status) as Diff;return <TR key={`${isRemoved?'old':'new'}-${e.id}`} className={isRemoved?'opacity-70':''}><TD><Badge variant={diffVariant(diff)}>{diff}</Badge></TD><TD><Badge variant={e.review_status==='valide'?'success':e.review_status==='rejete'?'danger':'warning'}>{e.review_status.replace('_',' ')}</Badge></TD><TD><div className="font-semibold">{e.commercial_name}</div>{!isRemoved&&!e.product_id&&e.review_status==='valide'&&<span className="text-caption text-danger">Non relié</span>}</TD><TD>{e.target_label}</TD><TD>{e.active_substances||'—'}</TD><TD>{e.phi_days??'—'} j</TD><TD>{e.dose_text||'—'}</TD><TD>{e.eu_uk_mrl_text||'—'}</TD><TD>{e.source_page||'—'}</TD><TD>{!isRemoved&&selected.status!=='remplacee'&&<Button size="icon-sm" variant="ghost" onClick={()=>setEditing({...e})} title="Contrôler"><Pencil size={13}/></Button>}</TD></TR>})}</tbody></DataTable>}</Card></>}
    {!selected&&<Card><div className="text-center py-xl"><CheckCircle2 className="mx-auto text-success mb-sm"/><p>Aucune liste positive importée pour ce client / cette société.</p></div></Card>}
    {editing&&<Modal title="CONTRÔLER LA LIGNE" size="lg" onClose={()=>setEditing(null)}><div className="grid grid-cols-1 md:grid-cols-2 gap-md"><Field label="Produit importé" required><Input value={editing.commercial_name} onChange={e=>setEditing({...editing,commercial_name:e.target.value})}/></Field><Field label="Relier au produit du référentiel" required={editing.review_status==='valide'}><Select value={editing.product_id||''} onChange={e=>setEditing({...editing,product_id:e.target.value||null})}><option value="">Non relié</option>{products.map(p=><option key={p.id} value={p.id}>{p.commercial_name}</option>)}</Select></Field><Field label="Cible importée" required><Input value={editing.target_label} onChange={e=>setEditing({...editing,target_label:e.target.value})}/></Field><Field label="Relier à la cible" required={editing.review_status==='valide'}><Select value={editing.target_id||''} onChange={e=>{const targetId=e.target.value||null;const selectedTarget=targets.find(target=>target.id===targetId);setEditing({...editing,target_id:targetId,target_label:selectedTarget?.canonical_name||editing.target_label})}}><option value="">Non reliée</option>{targets.map(t=><option key={t.id} value={t.id}>{t.canonical_name}</option>)}</Select></Field><Field label="Substance active"><Input value={editing.active_substances||''} onChange={e=>setEditing({...editing,active_substances:e.target.value})}/></Field><Field label="DAR (jours)"><Input type="number" min="0" value={editing.phi_days??''} onChange={e=>setEditing({...editing,phi_days:e.target.value===''?null:Number(e.target.value)})}/></Field><Field label="Dose"><Input value={editing.dose_text||''} onChange={e=>setEditing({...editing,dose_text:e.target.value})}/></Field><Field label="Mode de traitement"><Input value={editing.treatment_mode||''} onChange={e=>setEditing({...editing,treatment_mode:e.target.value})}/></Field><Field label="LMR EU / UK"><Input value={editing.eu_uk_mrl_text||''} onChange={e=>setEditing({...editing,eu_uk_mrl_text:e.target.value})}/></Field><Field label="LMR Suisse"><Input value={editing.swiss_mrl_text||''} onChange={e=>setEditing({...editing,swiss_mrl_text:e.target.value})}/></Field><Field label="Décision" className="md:col-span-2"><Select value={editing.review_status} onChange={e=>setEditing({...editing,review_status:e.target.value})}><option value="a_controler">À contrôler</option><option value="valide">Valider</option><option value="rejete">Rejeter</option></Select></Field><Field label="Données source" className="md:col-span-2"><Textarea readOnly value={`Page ${editing.source_page||'—'} · ${editing.commercial_name} · ${editing.target_label}`}/></Field></div><ModalFooter onCancel={()=>setEditing(null)} onSave={saveEntry} loading={busy} disabled={!editing.commercial_name||!editing.target_label||(editing.review_status==='valide'&&(!editing.product_id||!editing.target_id))}/></Modal>}
  </div>
}
