'use client'

import {useCallback,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,CheckCircle2,Combine,Eye,Pencil,Plus,Search,Target} from 'lucide-react'
import {toast} from 'sonner'
import {useAuth} from '@/lib/auth'
import {supabase} from '@/lib/supabase'
import {Badge} from '@/components/ui/Badge'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {DataTable,TD,TH,THead,TR} from '@/components/ui/DataTable'
import {EmptyState} from '@/components/ui/EmptyState'
import {Field,Input,Select} from '@/components/ui/Input'
import {Modal,ModalFooter} from '@/components/ui/Modal'
import {PageHeader} from '@/components/ui/PageHeader'

const CATEGORIES=[['ravageur','Ravageur'],['maladie','Maladie'],['acarien','Acarien'],['nematode','Nématode'],['adventice','Adventice'],['autre','Autre']]
const normalize=(value:string)=>(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')
const emptyForm={id:null as string|null,canonical_name:'',category:'autre',aliases:'',is_active:true}

export default function CiblesPage(){
  const {activeDomain,hasPermission}=useAuth()
  const [targets,setTargets]=useState<any[]>([]),[entries,setEntries]=useState<any[]>([]),[uses,setUses]=useState<any[]>([]),[stocks,setStocks]=useState<any[]>([])
  const [search,setSearch]=useState(''),[category,setCategory]=useState('toutes'),[form,setForm]=useState<any|null>(null),[mergeSource,setMergeSource]=useState<any|null>(null),[mergeDestination,setMergeDestination]=useState(''),[details,setDetails]=useState<any|null>(null),[saving,setSaving]=useState(false)
  const canEdit=hasPermission('agronomie','edit')
  const load=useCallback(async()=>{if(!activeDomain)return;const domain=activeDomain.domain_id;const [t,e,u,s]=await Promise.all([
    supabase.from('phyto_targets').select('*').order('canonical_name'),
    supabase.from('phyto_positive_list_entries').select('id,target_id,product_id,list_id,station_approved,review_status,commercial_name,phyto_positive_lists(version,status),plant_protection_products(commercial_name,authorization_status,safety_data_verified)').eq('domain_id',domain),
    supabase.from('product_authorized_uses').select('id,product_id,target_name,is_active').eq('domain_id',domain),
    supabase.from('stock_items').select('plant_protection_product_id,current_qty,is_active').eq('domain_id',domain).eq('category','phytosanitaires'),
  ]);if(t.error)toast.error(t.error.message);setTargets(t.data||[]);setEntries(e.data||[]);setUses(u.data||[]);setStocks(s.data||[])},[activeDomain?.domain_id])
  useEffect(()=>{load()},[load])
  const enriched=useMemo(()=>targets.map(target=>{const linked=entries.filter(entry=>entry.target_id===target.id);const productIds=new Set(linked.map(entry=>entry.product_id).filter(Boolean));const activeLists=new Set(linked.filter(entry=>(entry.phyto_positive_lists as any)?.status==='active'&&entry.station_approved).map(entry=>entry.list_id));const usable=linked.filter(entry=>{const product=entry.plant_protection_products as any;return entry.station_approved&&product?.authorization_status==='autorise'&&product?.safety_data_verified&&uses.some(use=>use.product_id===entry.product_id&&use.is_active&&normalize(use.target_name)===normalize(target.canonical_name))&&stocks.some(stock=>stock.plant_protection_product_id===entry.product_id&&stock.is_active&&Number(stock.current_qty)>0)}).length;return{...target,linked,productCount:productIds.size,listCount:activeLists.size,usable}}),[targets,entries,uses,stocks])
  const visible=enriched.filter(target=>(category==='toutes'||target.category===category)&&(!search||normalize(`${target.canonical_name} ${(target.aliases||[]).join(' ')}`).includes(normalize(search))))
  const save=async()=>{if(!form||!activeDomain)return;setSaving(true);const {error}=await supabase.rpc('save_phyto_target',{p_domain:activeDomain.domain_id,p_target_id:form.id,p_name:form.canonical_name,p_category:form.category,p_aliases:String(form.aliases).split(',').map(value=>value.trim()).filter(Boolean),p_is_active:form.is_active});setSaving(false);if(error)toast.error(error.message);else{toast.success(form.id?'Cible modifiée':'Cible créée');setForm(null);load()}}
  const merge=async()=>{if(!activeDomain||!mergeSource||!mergeDestination)return;setSaving(true);const {data,error}=await supabase.rpc('merge_phyto_targets',{p_domain:activeDomain.domain_id,p_source_id:mergeSource.id,p_destination_id:mergeDestination});setSaving(false);if(error)toast.error(error.message);else{toast.success(`${data.entries_moved} association(s) déplacée(s)`);setMergeSource(null);setMergeDestination('');load()}}
  const verify=async(target:any)=>{if(!activeDomain)return;const {error}=await supabase.rpc('verify_phyto_target',{p_domain:activeDomain.domain_id,p_target_id:target.id});if(error)toast.error(error.message);else{toast.success(`Cible ${target.canonical_name} vérifiée`);load()}}
  const detailRows=details?entries.filter(entry=>entry.target_id===details.id):[]
  return <div className="space-y-md">
    <Link href="/agronomie"><ArrowLeft size={12}/> Agronomie</Link>
    <PageHeader title="Cibles biologiques" subtitle="Référentiel phytosanitaire" icon={Target} iconColor="#84cc16" description={`${targets.filter(t=>t.is_active).length} cible(s) active(s)`} actions={canEdit?<Button onClick={()=>setForm({...emptyForm})}><Plus size={14}/> Nouvelle cible</Button>:undefined}/>
    <Card><div className="grid grid-cols-1 md:grid-cols-[1fr_220px] gap-md"><Field label="Rechercher"><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-fg-tertiary"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom ou alias…"/></div></Field><Field label="Catégorie"><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="toutes">Toutes</option>{CATEGORIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field></div></Card>
    {visible.length===0?<Card><EmptyState icon={Target} title="Aucune cible" description="Ajoutez une cible ou importez une liste positive."/></Card>:<Card padding="none"><DataTable minWidth={1050}><THead><TR><TH>Cible</TH><TH>Catégorie</TH><TH>Alias</TH><TH>Produits liés</TH><TH>Listes actives</TH><TH>Utilisables</TH><TH>Qualité</TH><TH>Statut</TH><TH></TH></TR></THead><tbody>{visible.map(target=><TR key={target.id}><TD><div className="font-semibold">{target.canonical_name||'Cible sans nom'}</div>{target.merged_into_id&&<span className="text-caption text-warning">Fusionnée</span>}</TD><TD><Badge variant="info">{CATEGORIES.find(([value])=>value===target.category)?.[1]||target.category}</Badge></TD><TD className="max-w-64">{(target.aliases||[]).join(', ')||'—'}</TD><TD mono>{target.productCount}</TD><TD mono>{target.listCount}</TD><TD mono><span className={target.usable?'text-success':'text-fg-tertiary'}>{target.usable}</span></TD><TD><Badge variant={target.is_verified?'success':'warning'}>{target.is_verified?'Vérifiée':'À vérifier'}</Badge></TD><TD><Badge variant={target.is_active?'success':'default'}>{target.is_active?'Active':'Inactive'}</Badge></TD><TD><div className="flex gap-xs"><Button size="icon-sm" variant="ghost" title="Voir les produits" onClick={()=>setDetails(target)}><Eye size={13}/></Button>{canEdit&&<>{!target.is_verified&&target.is_active&&<Button size="icon-sm" variant="secondary" title="Valider cette cible" onClick={()=>verify(target)}><CheckCircle2 size={13}/></Button>}<Button size="icon-sm" variant="ghost" title="Modifier" onClick={()=>setForm({...target,aliases:(target.aliases||[]).join(', ')})}><Pencil size={13}/></Button><Button size="icon-sm" variant="ghost" title="Fusionner" onClick={()=>setMergeSource(target)}><Combine size={13}/></Button></>}</div></TD></TR>)}</tbody></DataTable></Card>}
    {form&&<Modal title={form.id?'MODIFIER LA CIBLE':'NOUVELLE CIBLE'} onClose={()=>setForm(null)}><div className="space-y-md"><Field label="Nom canonique" required><Input value={form.canonical_name} onChange={e=>setForm({...form,canonical_name:e.target.value})}/></Field><Field label="Catégorie" required><Select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Alias" hint="Séparez les synonymes par des virgules. Exemple : Aleurode, Aleurodes"><Input value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})}/></Field><label className="flex items-center gap-xs text-body-sm"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Cible active</label><ModalFooter onCancel={()=>setForm(null)} onSave={save} loading={saving} disabled={!form.canonical_name.trim()}/></div></Modal>}
    {mergeSource&&<Modal title="FUSIONNER UNE CIBLE" onClose={()=>setMergeSource(null)}><div className="space-y-md"><p className="text-body-sm">Les associations de <strong>{mergeSource.canonical_name}</strong> seront déplacées vers la cible choisie. L’ancien nom sera conservé comme alias.</p><Field label="Cible de destination" required><Select value={mergeDestination} onChange={e=>setMergeDestination(e.target.value)}><option value="">Sélectionner</option>{targets.filter(target=>target.id!==mergeSource.id&&target.is_active&&!target.merged_into_id).map(target=><option key={target.id} value={target.id}>{target.canonical_name}</option>)}</Select></Field><ModalFooter onCancel={()=>setMergeSource(null)} onSave={merge} loading={saving} disabled={!mergeDestination} saveLabel="FUSIONNER"/></div></Modal>}
    {details&&<Modal title={`PRODUITS — ${details.canonical_name}`} size="lg" onClose={()=>setDetails(null)}><div className="space-y-sm">{detailRows.length===0?<p className="text-fg-tertiary">Aucun produit associé pour le client actif.</p>:detailRows.map(entry=>{const product=entry.plant_protection_products as any;const list=entry.phyto_positive_lists as any;const hasStock=stocks.some(stock=>stock.plant_protection_product_id===entry.product_id&&stock.is_active);return <Card key={entry.id} padding="sm"><div className="flex justify-between gap-md"><div><div className="font-semibold">{product?.commercial_name||entry.commercial_name}</div><div className="text-caption text-fg-tertiary">Liste {list?.version||'—'} · {list?.status||'—'}</div></div><div className="flex flex-wrap gap-xs"><Badge variant={entry.station_approved?'success':'warning'}>{entry.station_approved?'Station validée':'Station à valider'}</Badge><Badge variant={product?.authorization_status==='autorise'&&product?.safety_data_verified?'success':'warning'}>{product?.authorization_status==='autorise'&&product?.safety_data_verified?'ONSSA vérifié':'ONSSA à vérifier'}</Badge><Badge variant={hasStock?'success':'default'}>{hasStock?'Stock lié':'Sans stock'}</Badge></div></div></Card>})}</div></Modal>}
  </div>
}
